### ISSUE TITLE
Blink when animation loops

### ISSUE THREAD

**Issue by wtmoose** [airbnb/lottie-ios#122] opened 2017-02-24 01:13 UTC
Animation blinks just before looping. If you play this on a loop, there is a green frame displayed between the last and first frames. The green frame is not present in After Effects and the designer has tried multiple revisions.

Any suggestions?

We had a similar animation with only 2 colors and it took the designer 8 iterations to eliminate the blink. No luck with this one so far.

[ColorBar.json.zip](https://github.com/airbnb/lottie-ios/files/798134/ColorBar.json.zip)

**Comment by therealsalih** [comment] 2017-02-24 01:43
Hi @wtmoose can you attach the AE file?

**Comment by wtmoose** [comment] 2017-02-24 02:04
Sure!

[AppAssets.aep.zip](https://github.com/airbnb/lottie-ios/files/798201/AppAssets.aep.zip)

**Comment by buba447** [comment] 2017-02-24 18:11
@wtmoose I just ran it in the test project and did not see a blink. Any suggestions on how to reproduce?

**Comment by wtmoose** [comment] 2017-02-24 18:55
@buba447 thank you for taking a look! Please try this sample project.

Notice the green blip at the end of the orange color bar animation.

[ColorBar.zip](https://github.com/airbnb/lottie-ios/files/800200/ColorBar.zip)

**Comment by buba447** [comment] 2017-02-25 00:02
[colorbar.mov.zip](https://github.com/airbnb/lottie-ios/files/800742/colorbar.mov.zip)

Hmmm im not seeing it over here. I wonder if its a version thing. I didn't try running on device since theres no lightning cable around me right now.
Are you seeing it on device too?

**Comment by buba447** [comment] 2017-02-25 00:03
@wtmoose

**Comment by buba447** [comment] 2017-02-25 00:04
Ahhh! I see it on the iOS 6 simulator but not the 7....

**Comment by buba447** [comment] 2017-02-25 00:05
But only on the first loop.
Might be a simulator issue. Gonna try it on device soon as i find a lightning cable.

**Comment by wtmoose** [comment] 2017-02-25 00:51
Interesting. I see it on iPhone 7 simulator running Xcode 8.2.1 and on my iPhone 7+ running 10.2.1. It does it on every cycle for me.

**Comment by wtmoose** [comment] 2017-02-25 01:06
Here are some additional results:

Simulator iPhone 7: blinks always
Simulator iPhone 7+: blinks first loop
Device iPhone 7+: blinks always

Here is a recording of my iPhone 7+ device:

[ColorBar iPhone 7plus.zip](https://github.com/airbnb/lottie-ios/files/800794/ColorBar.iPhone.7plus.zip)

**Comment by wtmoose** [comment] 2017-02-25 18:28
After looking at this further, I think the inconsistency in Simulator is because it drops frames, which sometimes include the blip.

But the good news is I found a workaround by changing the following values on "Shape Layer 4":

<img width="784" alt="screen shot 2017-02-25 at 12 24 16 pm" src="https://cloud.githubusercontent.com/assets/2529176/23333697/935be2d6-fb55-11e6-99ea-881fb382a182.png">

I'm going to leave the ticket open since this seems like a bug.

Thanks!

**Comment by buba447** [comment] 2017-02-27 19:21
Hmmm. Ill look into this!
Thank you for digging into it!

**Comment by kiroskirin** [comment] 2017-03-09 03:22
@wtmoose @buba447 I face the same issue when I use JSON animation with 1 loop, but when extend animation more than 1 loop ( in my case I extend 3 loops like a PinJump) it appear that blinking is gone.

**Comment by PavelLaptev** [comment] 2017-04-18 17:47
I have the same problem. Changing `ip` don't work for me.

**Comment by buba447** [comment] 2017-08-02 22:32
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Closed by buba447** 2017-08-02 22:32 UTC
