### ISSUE TITLE
Missing platform compatibility imports

### ISSUE THREAD

**Issue by benpious** [airbnb/lottie-ios#135] opened 2017-02-27 23:00 UTC
Several files in Lottie's MacCompatibility folder don't import `lotplatformcompat.h`. For some reason this builds fine in the sample project, but in the project I'm working in (which does not use Cocoapods or Carthage) this leads to compilation issues, because `TARGET_OS_IPHONE` and `TARGET_IPHONE_SIMULATOR` aren't defined. 

The files are:

Classes/MacCompatability/CADisplayLink.m
Classes/MacCompatability/NSValue+Compat.h
Classes/MacCompatability/NSValue+Compat.m
Classes/MacCompatability/UIColor.m

All the other files in that directory do import the platform compatibility header. This isn't intended, right?

**Comment by buba447** [comment] 2017-02-27 23:36
LOTPlayformCompat is used to import the files you have mentioned. It is an umbrella header to import the proper frameworks, or their open source replacements (such as the UIColor)
Seems like the problem is actually that the LOTPlatformCompat isn't properly added in the Lottie project in the root.
Are you importing that project manually or importing the files yourself?

**Comment by buba447** [comment] 2017-02-27 23:38
I just merged a fix into master. Check it out here https://github.com/airbnb/lottie-ios/pull/138
or just pull master :) 
Feel free to reopen and comment if it doesn't fix your issue.

**Comment by buba447** [comment] 2017-02-27 23:39
@benpious

**Closed by buba447** 2017-02-27 23:38 UTC

**Comment by benpious** [comment] 2017-02-28 01:15
Unfortunately, this definitely won't fix the issue I'm having. The project I'm working on uses Buck, which means that we don't actually use the .xcodeproj file included in this repo, but instead generate our own from a BUCK file. 

Also, correct me if I'm wrong, but it also looks from the diff like your fix is for an unrelated issue with building for MacOS, I'm actually using Lottie in an iOS app. 

Just to clarify what I think the issue is; the files I listed don't import that umbrella header; but the real issue is that they therefore don't import `TargetConditionals.h`, which is imported in the umbrella header. Therefore, they don't have `TARGET_OS_IPHONE` defined, or any of the other symbols defined in that header, so the wrong branch of the ifdef is taken, causing the build to fail, since none of the MacOS compatibility stuff was meant to be compiled for iOS. 

Normally, you don't have to worry about this because you import Foundation first, which includes `TargetConditionals.h`, but since Lottie doesn't import Foundation until after it does the check, it isn't imported yet. Again, not sure why it builds in the project that comes with Lottie, but I do know that when I add those imports myself, it fixes the problem. 

I can do a pull request adding the import, but I wanted to make sure that there wasn't something I was missing first.

**Comment by SoniyaHadkar** [comment] 2017-07-25 20:24
We have similar issue with the latest code base. We are not using cocoapods or carthage in the project.
We tried to create FAT binary by building the source code with Device and Simulator and using Lipo, that does not work. (as I guess for simulator we need i386 and x86_64 to be exported.)

Any thoughts?
