### ISSUE TITLE
Xcode16 'CAAnimationCalculationMode' is only available in iOS 12.0 or newer

### ISSUE THREAD

**Issue by Yck-Dakucha** [airbnb/lottie-ios#2426] opened 2024-06-11 03:36 UTC
Xcode16 can’t build

* 'CAAnimationCalculationMode' is only available in iOS 12.0 or newer
* 'CAShapeLayerFillRule' is only available in iOS 12.0 or newer
* 'CAShapeLayerLineJoin' is only available in iOS 12.0 or newer
* 'CAShapeLayerLineCap' is only available in iOS 12.0 or newer
* 'CATextLayerAlignmentMode' is only available in iOS 12.0 or newer

![image](https://github.com/airbnb/lottie-ios/assets/12741176/7e24b951-6885-4ff2-b418-1cc96adc117b)

**Comment by andre-alves** [comment] 2024-06-11 15:27
Fixed in Lottie 4.4.2 or later. Can you update?

**Comment by lucasromanomr** [comment] 2024-06-11 23:18
The big problem is that above version 4.4.2 there is no longer support for iOS12, because the minimum target was for iOS13, so applications that depend on iOS12 can no longer use lottie. Unless you make changes to work with iOS12 and take appropriate treatments

**Comment by Yck-Dakucha** [comment] 2024-06-12 03:05
> Fixed in Lottie 4.4.2 or later. Can you test the latest version?

sorry, i can't use 4.4.2, because my app need support iOS11

**Comment by calda** [comment] 2024-06-12 03:21
Yes, Lottie now only supports iOS 13+. Older versions of Lottie still support iOS 12 and earlier.

**Closed by calda** 2024-06-12 03:21 UTC

**Comment by Axk520** [comment] 2024-06-17 07:20
😭

**Comment by calda** [comment] 2024-06-17 13:59
So far I don't think this specific error is related to Lottie dropping support for iOS 12.

> `'CAShapeLayerFillRule' is only available in iOS 12.0 or newer`

So there is no issue here -- `CAShapeLayerFillRule` requires iOS 12+, and so does Lottie. `CAShapeLayerFillRule` is only supported in iOS 11, which Lottie doesn't support.

Unless folks are actually relying on _iOS 11 support_, I think that specific error may be a red herring.

**Comment by calda** [comment] 2024-06-17 14:03
**If you're currently using `lottie-ios` or `lottie-spm` 4.4.3 with Xcode 15, then it should also work correctly with Xcode 16**. 

Any new Xcode 16 errors related to iOS 12 are almost certainly _not_ the root cause of any issue.

If you're still having issues, try things like a clean build and deleting derived data, or try using `lottie-ios` instead of `lottie-spm` for now.

**Comment by calda** [comment] 2024-06-17 18:41
Here's a sample project that uses lottie-spm 4.4.3 and compiles as expected using Xcode 16: 
[lottie-spm-Xcode-16-sample-app.zip](https://github.com/user-attachments/files/15875569/lottie-spm-Xcode-16-sample-app.zip)
