### ISSUE TITLE
Incorrect text vertical positioning; animation movements opposite of expected.

### ISSUE THREAD

**Issue by ebridges** [airbnb/lottie-ios#1127] opened 2020-02-14 20:40 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.6

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

_These correspond to the animation json attached at the bottom._

**Title Card (Correct) - Start:**
* "Photographer" moves down into position, "Fiona" moves up.
![Title card correct - start](https://user-images.githubusercontent.com/1581123/74568010-114fc680-4f45-11ea-965d-11c2f5da0303.png)

**Title Card (Correct) - End:**
![Title card correct - end](https://user-images.githubusercontent.com/1581123/74568037-2167a600-4f45-11ea-8063-8b64acb27467.png)

**Text Insert (Correct)**
![Text Insert correct](https://user-images.githubusercontent.com/1581123/74568179-6ab7f580-4f45-11ea-86cc-51b9056c2edd.png)

## Actual Behavior

**Title Card (Error) - Start:**
* Note: "Photographer" moves up to center, it is also incorrectly positioned horizontally. "Fiona" is offscreen to the left.
![Title card error - start](https://user-images.githubusercontent.com/1581123/74568278-9a66fd80-4f45-11ea-82b6-73a11fe47bd4.png)

**Title Card (Error) - End:**
* Note: final position is off horizontally. Because it's centered vertically you might not notice that issue.
![Title card error - end](https://user-images.githubusercontent.com/1581123/74568349-c6827e80-4f45-11ea-8fde-c283d2c3ba52.png)

**Text Insert (Error)**
* The text is out of position vertically.
![Text Insert error](https://user-images.githubusercontent.com/1581123/74568423-f29dff80-4f45-11ea-9c36-55f006dc7057.png)

## Code Example

Create an AE project with text layer that is positioned other than in the center vertically and/or attach a transform with keyframes that move it in the vertical direction.

The text will be positioned incorrectly, for example, if it is sitting at the bottom of the screen in AE, it will shifted to above the screen.

If, for example, an animation is setup to start near the bottom and move upwards it will do the opposite.

### Possible Fix

It appears this is an issue caused by the differing coordinate system used in Core Graphics. If one takes the animation json file and parses through it to manipulate the anchor points and positions to account for this, the animation will show correctly. For example, the position vector's `y` value would be subtracted from the parent layer's height to get the corrected value. This is true even if the parent layer is a null layer with 0 height. The anchor's `y` value would  be inverted `(y' = -y)`.

In addition, going back to TextCompositionLayer, I believe that there should not be any anchor point adjustments made at all and the 'normalizedAnchor' should be constant = (0,1). Examining the code, it seemed to me that the layer's transform was taking everything into account and no further adjustments to the text positioning were necessary. Just to flip its `y` reference point.

## Animation JSON

<details>
<summary>
Text Insert: is off the screen (sits on top of screen instead of bottom).
</summary>
<p>

```json
{
   "v":"5.5.8",
   "fr":30,
   "ip":0,
   "op":450,
   "w":1920,
   "h":1080,
   "nm":"01_Intro_Insert_02",
   "ddd":0,
   "assets":[

   ],
   "fonts":{
      "list":[
         {
            "origin":0,
            "fPath":"",
            "fClass":"",
            "fFamily":"Canela",
            "fWeight":"",
            "fStyle":"Regular",
            "fName":"Canela-Regular",
            "ascent":71.8994140625
         }
      ]
   },
   "layers":[
      {
         "ddd":0,
         "ind":1,
         "ty":5,
         "nm":"My art is about bringing out the personality of my subjects, an",
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":100,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10
            },
            "p":{
               "a":0,
               "k":[
                  79,
                  611.722,
                  0
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  0,
                  0,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":0,
               "k":[
                  100,
                  100,
                  100
               ],
               "ix":6
            }
         },
         "ao":0,
         "t":{
            "d":{
               "k":[
                  {
                     "s":{
                        "sz":[
                           1217.109375,
                           979.173889160156
                        ],
                        "ps":[
                           0,
                           0
                        ],
                        "s":70,
                        "f":"Canela-Regular",
                        "t":"<TEXT0>",
                        "j":0,
                        "tr":10,
                        "lh":82,
                        "ls":0,
                        "fc":[
                           1,
                           1,
                           1
                        ]
                     },
                     "t":0
                  }
               ]
            },
            "p":{

            },
            "m":{
               "g":1,
               "a":{
                  "a":0,
                  "k":[
                     0,
                     0
                  ],
                  "ix":2
               }
            },
            "a":[
               {
                  "nm":"Animator 1",
                  "s":{
                     "t":0,
                     "xe":{
                        "a":0,
                        "k":0,
                        "ix":7
                     },
                     "ne":{
                        "a":0,
                        "k":0,
                        "ix":8
                     },
                     "a":{
                        "a":0,
                        "k":100,
                        "ix":4
                     },
                     "b":1,
                     "rn":0,
                     "sh":1,
                     "r":1
                  },
                  "a":{
                     "a":{
                        "a":0,
                        "k":[
                           0,
                           0,
                           0
                        ],
                        "ix":1
                     },
                     "p":{
                        "a":0,
                        "k":[
                           0,
                           -30,
                           0
                        ],
                        "ix":2
                     },
                     "s":{
                        "a":0,
                        "k":[
                           100,
                           100,
                           100
                        ],
                        "ix":3
                     },
                     "sk":{
                        "a":0,
                        "k":0,
                        "ix":4
                     },
                     "sa":{
                        "a":0,
                        "k":0,
                        "ix":5
                     },
                     "r":{
                        "a":0,
                        "k":0,
                        "ix":8
                     },
                     "o":{
                        "a":0,
                        "k":0,
                        "ix":9
                     }
                  }
               },
               {
                  "nm":"Animator 2",
                  "s":{
                     "t":0,
                     "xe":{
                        "a":0,
                        "k":100,
                        "ix":7
                     },
                     "ne":{
                        "a":0,
                        "k":0,
                        "ix":8
                     },
                     "a":{
                        "a":0,
                        "k":100,
                        "ix":4
                     },
                     "b":1,
                     "rn":0,
                     "sh":3,
                     "o":{
                        "a":1,
                        "k":[
                           {
                              "i":{
                                 "x":[
                                    0.415
                                 ],
                                 "y":[
                                    1
                                 ]
                              },
                              "o":{
                                 "x":[
                                    0.317
                                 ],
                                 "y":[
                                    0
                                 ]
                              },
                              "t":20,
                              "s":[
                                 -100
                              ]
                           },
                           {
                              "t":101,
                              "s":[
                                 40
                              ]
                           }
                        ],
                        "ix":3
                     },
                     "r":1
                  },
                  "a":{
                     "a":{
                        "a":0,
                        "k":[
                           0,
                           0,
                           0
                        ],
                        "ix":1
                     },
                     "p":{
                        "a":0,
                        "k":[
                           0,
                           30,
                           0
                        ],
                        "ix":2
                     },
                     "s":{
                        "a":0,
                        "k":[
                           100,
                           100,
                           100
                        ],
                        "ix":3
                     },
                     "sk":{
                        "a":0,
                        "k":0,
                        "ix":4
                     },
                     "sa":{
                        "a":0,
                        "k":0,
                        "ix":5
                     },
                     "r":{
                        "a":0,
                        "k":0,
                        "ix":8
                     },
                     "o":{
                        "a":0,
                        "k":0,
                        "ix":9
                     }
                  }
               },
               {
                  "nm":"Animator 3",
                  "s":{
                     "t":0,
                     "xe":{
                        "a":0,
                        "k":100,
                        "ix":7
                     },
                     "ne":{
                        "a":0,
                        "k":0,
                        "ix":8
                     },
                     "a":{
                        "a":0,
                        "k":100,
                        "ix":4
                     },
                     "b":1,
                     "rn":0,
                     "sh":3,
                     "o":{
                        "a":1,
                        "k":[
                           {
                              "i":{
                                 "x":[
                                    0.415
                                 ],
                                 "y":[
                                    1
                                 ]
                              },
                              "o":{
                                 "x":[
                                    0.317
                                 ],
                                 "y":[
                                    0
                                 ]
                              },
                              "t":20,
                              "s":[
                                 -100
                              ]
                           },
                           {
                              "t":101,
                              "s":[
                                 40
                              ]
                           }
                        ],
                        "ix":3
                     },
                     "r":1
                  },
                  "a":{
                     "a":{
                        "a":0,
                        "k":[
                           0,
                           0,
                           0
                        ],
                        "ix":1
                     },
                     "p":{
                        "a":0,
                        "k":[
                           0,
                           0,
                           0
                        ],
                        "ix":2
                     },
                     "s":{
                        "a":0,
                        "k":[
                           100,
                           100,
                           100
                        ],
                        "ix":3
                     },
                     "sk":{
                        "a":0,
                        "k":0,
                        "ix":4
                     },
                     "sa":{
                        "a":0,
                        "k":0,
                        "ix":5
                     },
                     "r":{
                        "a":0,
                        "k":0,
                        "ix":8
                     },
                     "o":{
                        "a":0,
                        "k":100,
                        "ix":9
                     }
                  }
               }
            ]
         },
         "ip":20,
         "op":450,
         "st":20,
         "bm":0
      }
   ],
   "markers":[

   ]
}
```

</p>
</details>

<details>
<summary>
Title Card: will show the animations going in the opposite direction 
</summary>
<p>

```json
{
   "v":"5.5.8",
   "fr":30,
   "ip":0,
   "op":150,
   "w":1920,
   "h":1080,
   "nm":"01_Intro_TitleCard_03",
   "ddd":0,
   "assets":[

   ],
   "fonts":{
      "list":[
         {
            "origin":0,
            "fPath":"",
            "fClass":"",
            "fFamily":"Canela",
            "fWeight":"",
            "fStyle":"Regular",
            "fName":"Canela-Regular",
            "ascent":71.8994140625
         },
         {
            "origin":0,
            "fPath":"",
            "fClass":"",
            "fFamily":"Sharp Sans No1 Semibold",
            "fWeight":"",
            "fStyle":"Regular",
            "fName":"SharpSansNo1-Semibold",
            "ascent":72.9995727539062
         }
      ]
   },
   "layers":[
      {
         "ddd":0,
         "ind":2,
         "ty":3,
         "nm":"Main Null",
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":0,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10
            },
            "p":{
               "a":0,
               "k":[
                  1014.5,
                  529,
                  0
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  0,
                  0,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":0,
               "k":[
                  100,
                  100,
                  100
               ],
               "ix":6
            }
         },
         "ao":0,
         "ip":0,
         "op":300,
         "st":0,
         "bm":0
      },
      {
         "ddd":0,
         "ind":3,
         "ty":3,
         "nm":"Null 1",
         "parent":2,
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":0,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10
            },
            "p":{
               "a":1,
               "k":[
                  {
                     "i":{
                        "x":0.079,
                        "y":1
                     },
                     "o":{
                        "x":0.64,
                        "y":0
                     },
                     "t":18,
                     "s":[
                        -324,
                        140,
                        0
                     ],
                     "to":[
                        0,
                        0,
                        0
                     ],
                     "ti":[
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "t":36,
                     "s":[
                        -324,
                        0,
                        0
                     ]
                  }
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  0,
                  0,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":0,
               "k":[
                  100,
                  100,
                  100
               ],
               "ix":6
            }
         },
         "ao":0,
         "ip":18,
         "op":313,
         "st":13,
         "bm":0
      },
      {
         "ddd":0,
         "ind":4,
         "ty":5,
         "nm":"Fiona Walker",
         "parent":3,
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":100,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10
            },
            "p":{
               "a":0,
               "k":[
                  -1220,
                  -26,
                  0
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  0,
                  0,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":0,
               "k":[
                  100,
                  100,
                  100
               ],
               "ix":6
            }
         },
         "ao":0,
         "ef":[
            {
               "ty":28,
               "nm":"Set Matte",
               "np":8,
               "mn":"ADBE Set Matte3",
               "ix":1,
               "en":1,
               "ef":[
                  {
                     "ty":10,
                     "nm":"Take Matte From Layer",
                     "mn":"ADBE Set Matte3-0001",
                     "ix":1,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":1
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Use For Matte",
                     "mn":"ADBE Set Matte3-0002",
                     "ix":2,
                     "v":{
                        "a":0,
                        "k":4,
                        "ix":2
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Invert Matte",
                     "mn":"ADBE Set Matte3-0003",
                     "ix":3,
                     "v":{
                        "a":0,
                        "k":0,
                        "ix":3
                     }
                  },
                  {
                     "ty":7,
                     "nm":"If Layer Sizes Differ",
                     "mn":"ADBE Set Matte3-0004",
                     "ix":4,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":4
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Composite Matte with Original",
                     "mn":"ADBE Set Matte3-0005",
                     "ix":5,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":5
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Premultiply Matte Layer",
                     "mn":"ADBE Set Matte3-0006",
                     "ix":6,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":6
                     }
                  }
               ]
            }
         ],
         "t":{
            "d":{
               "k":[
                  {
                     "s":{
                        "sz":[
                           1269,
                           140.111389160156
                        ],
                        "ps":[
                           180.000061035156,
                           0
                        ],
                        "s":70,
                        "f":"SharpSansNo1-Semibold",
                        "t":"Fiona Walker",
                        "j":1,
                        "tr":10,
                        "lh":84,
                        "ls":0,
                        "fc":[
                           1,
                           1,
                           1
                        ]
                     },
                     "t":0
                  }
               ]
            },
            "p":{

            },
            "m":{
               "g":1,
               "a":{
                  "a":0,
                  "k":[
                     0,
                     0
                  ],
                  "ix":2
               }
            },
            "a":[

            ]
         },
         "ip":20,
         "op":320,
         "st":22,
         "bm":0
      },
      {
         "ddd":0,
         "ind":5,
         "ty":3,
         "nm":"Null 1",
         "parent":2,
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":0,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10
            },
            "p":{
               "a":1,
               "k":[
                  {
                     "i":{
                        "x":0.079,
                        "y":1
                     },
                     "o":{
                        "x":0.64,
                        "y":0
                     },
                     "t":18,
                     "s":[
                        210,
                        -123,
                        0
                     ],
                     "to":[
                        0,
                        0,
                        0
                     ],
                     "ti":[
                        0,
                        0,
                        0
                     ]
                  },
                  {
                     "t":36,
                     "s":[
                        210,
                        0,
                        0
                     ]
                  }
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  0,
                  0,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":0,
               "k":[
                  100,
                  100,
                  100
               ],
               "ix":6
            }
         },
         "ao":0,
         "ip":18,
         "op":318,
         "st":18,
         "bm":0
      },
      {
         "ddd":0,
         "ind":6,
         "ty":5,
         "nm":"Photographer",
         "parent":5,
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":100,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10
            },
            "p":{
               "a":0,
               "k":[
                  -11.923,
                  11.69,
                  0
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  200.077,
                  34.968,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":0,
               "k":[
                  100,
                  100,
                  100
               ],
               "ix":6
            }
         },
         "ao":0,
         "ef":[
            {
               "ty":28,
               "nm":"Set Matte",
               "np":8,
               "mn":"ADBE Set Matte3",
               "ix":1,
               "en":1,
               "ef":[
                  {
                     "ty":10,
                     "nm":"Take Matte From Layer",
                     "mn":"ADBE Set Matte3-0001",
                     "ix":1,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":1
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Use For Matte",
                     "mn":"ADBE Set Matte3-0002",
                     "ix":2,
                     "v":{
                        "a":0,
                        "k":4,
                        "ix":2
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Invert Matte",
                     "mn":"ADBE Set Matte3-0003",
                     "ix":3,
                     "v":{
                        "a":0,
                        "k":0,
                        "ix":3
                     }
                  },
                  {
                     "ty":7,
                     "nm":"If Layer Sizes Differ",
                     "mn":"ADBE Set Matte3-0004",
                     "ix":4,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":4
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Composite Matte with Original",
                     "mn":"ADBE Set Matte3-0005",
                     "ix":5,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":5
                     }
                  },
                  {
                     "ty":7,
                     "nm":"Premultiply Matte Layer",
                     "mn":"ADBE Set Matte3-0006",
                     "ix":6,
                     "v":{
                        "a":0,
                        "k":1,
                        "ix":6
                     }
                  }
               ]
            }
         ],
         "t":{
            "d":{
               "k":[
                  {
                     "s":{
                        "sz":[
                           1677,
                           140.111389160156
                        ],
                        "ps":[
                           0,
                           0
                        ],
                        "s":70,
                        "f":"Canela-Regular",
                        "t":"Photographer",
                        "j":0,
                        "tr":10,
                        "lh":84,
                        "ls":0,
                        "fc":[
                           1,
                           1,
                           1
                        ]
                     },
                     "t":0
                  }
               ]
            },
            "p":{

            },
            "m":{
               "g":1,
               "a":{
                  "a":0,
                  "k":[
                     0,
                     0
                  ],
                  "ix":2
               }
            },
            "a":[

            ]
         },
         "ip":20,
         "op":320,
         "st":20,
         "bm":0
      },
      {
         "ddd":0,
         "ind":7,
         "ty":5,
         "nm":"Line",
         "parent":2,
         "sr":1,
         "ks":{
            "o":{
               "a":0,
               "k":100,
               "ix":11
            },
            "r":{
               "a":0,
               "k":0,
               "ix":10,
               "x":"var $bm_rt;\n$bm_rt = $bm_mul(time, 350);"
            },
            "p":{
               "a":0,
               "k":[
                  -43,
                  11.373,
                  0
               ],
               "ix":2
            },
            "a":{
               "a":0,
               "k":[
                  27.493,
                  34.651,
                  0
               ],
               "ix":1
            },
            "s":{
               "a":1,
               "k":[
                  {
                     "i":{
                        "x":[
                           0.667,
                           0.667,
                           0.667
                        ],
                        "y":[
                           1,
                           1,
                           1
                        ]
                     },
                     "o":{
                        "x":[
                           0.167,
                           0.167,
                           0.167
                        ],
                        "y":[
                           0.167,
                           0,
                           0
                        ]
                     },
                     "t":23,
                     "s":[
                        0,
                        100,
                        100
                     ]
                  },
                  {
                     "t":34,
                     "s":[
                        100,
                        100,
                        100
                     ]
                  }
               ],
               "ix":6
            }
         },
         "ao":0,
         "t":{
            "d":{
               "k":[
                  {
                     "s":{
                        "sz":[
                           1677,
                           140.111389160156
                        ],
                        "ps":[
                           0,
                           0
                        ],
                        "s":70,
                        "f":"Canela-Regular",
                        "t":"—",
                        "j":0,
                        "tr":10,
                        "lh":84,
                        "ls":0,
                        "fc":[
                           1,
                           1,
                           1
                        ]
                     },
                     "t":0
                  }
               ]
            },
            "p":{

            },
            "m":{
               "g":1,
               "a":{
                  "a":0,
                  "k":[
                     0,
                     0
                  ],
                  "ix":2
               }
            },
            "a":[

            ]
         },
         "ip":23,
         "op":311,
         "st":11,
         "bm":0
      }
   ],
   "markers":[

   ]
}

```

</p>
</details>

**Comment by DSalman** [comment] 2020-04-14 14:06
This appears to be use-case dependent. When adding the Lottie animation as a sublayer to a CALayer tree, the setting of the 'geometryFlipped' flag must be taken into account. Since sublayers take on the value of the super-layer's (in most circumstances) the setting can cause unintended consequences further down the layer stack. I believe Lottie works as intended when placed in a conventional UIView based object since the view's backing layer probably is flipped for the UI coordinate system.

**Comment by buba447** [comment] 2020-04-23 17:08
It should be fixed by https://github.com/airbnb/lottie-ios/releases/tag/3.1.7

**Closed by buba447** 2020-04-23 17:08 UTC

**Comment by buba447** [comment] 2020-04-23 17:32
Correction https://github.com/airbnb/lottie-ios/releases/tag/3.1.8
