### ISSUE TITLE
Does it support manual installation?

### ISSUE THREAD

**Issue by WGFcode** [airbnb/lottie-ios#1401] opened 2021-10-13 02:52 UTC
## What Platform are you on? 

- [] iOS

## What Language are you in?
- [] Swift

**Comment by calda** [comment] 2022-07-13 17:31
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:31 UTC
