### ISSUE TITLE
Documentation for exporting Lottie Animations to video

### ISSUE THREAD

**Issue by Andy4202** [airbnb/lottie-ios#891] opened 2019-04-25 22:03 UTC
Would it be possible to provide documentation on exporting Lottie Animations to video with AVAssetExportSession?

Thank you.

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

**Comment by buba447** [comment] 2019-11-26 16:54
Duplicate of https://github.com/airbnb/lottie-ios/issues/1001

**Closed by buba447** 2019-11-26 16:54 UTC
