### ISSUE TITLE
Support Gif export?

### ISSUE THREAD

**Issue by zhangjunmax** [airbnb/lottie-ios#835] opened 2019-03-29 08:43 UTC
Support Gif export?

**Comment by xiaohange** [comment] 2019-04-25 09:42
The same question

**Comment by KONGFANJI** [comment] 2019-08-17 09:41
The same too

**Comment by mayqiyue** [comment] 2019-10-18 10:07
The same too

**Comment by buba447** [comment] 2019-11-26 16:54
Duplicate of https://github.com/airbnb/lottie-ios/issues/1001

Closing and merging issues to reduce noise.

**Closed by buba447** 2019-11-26 16:54 UTC
