### ISSUE TITLE
Storyboard referencing `AnimationView` causes crash in Lottie 3.5.0

### ISSUE THREAD

**Issue by brian-voong** [airbnb/lottie-ios#1771] opened 2022-10-13 17:17 UTC
## Which Version of Lottie are you using?

Lottie 3.5.0

The following crashes are showing up in 3.5.0 after updating from 3.4.4:

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/102084882/195662862-a919acba-14f9-47e6-b264-c5d5aee555a2.png">

Reverting back to 3.4.4, these crashes go away.

**Comment by calda** [comment] 2022-10-13 17:17
Could you share a sample project that reproduces this issue?

**Comment by brian-voong** [comment] 2022-10-13 17:59
Currently not able to repro this with a brand new project, I'll take another stab at it once I get some free cycles again.

**Comment by brian-voong** [comment] 2022-10-13 18:06
Bad Access: 

![image](https://user-images.githubusercontent.com/102084882/195672744-eedef3c4-4fc2-4a98-9e14-d6c47be7e787.png)

**Comment by zypherman** [comment] 2022-10-13 20:34
I will work on getting more info from my development team but I can second the new crashes we are seeing after upgrading to 3.5.0.

**Comment by SajjadN92** [comment] 2022-10-14 07:53
The same issue, after updating to version 3.5.0

**Comment by alextudge** [comment] 2022-10-14 13:29
Same issue here! Seems to be caused by:
a) having `AnimationView` referenced a storyboard
b) using `LottieAnimation.named(:` to initialise an AnimationView's animation, or initialising an LottieAnimationView's animation view `Animation.named(:`

**Comment by calda** [comment] 2022-10-14 15:03
Ohhh, interesting! It sounds like changing `AnimationView` from a class to a typealias is source-compatible for Swift code but not for storyboards. Thanks for the info.

I don't think there's a fix for this on our side -- storyboards will just need to he updated to use `LottieAnimationView` instead of `AnimationView`. We're removing the old `AnimationView` declaration completely in Lottie 4.0 this month, which will hopefully change this cryptic error into something easier to understand (e.g. "no type named AnimationView").

**Comment by calda** [comment] 2022-10-14 15:04
I'll keep this issue open until we release Lottie 4.0, for visibility.

**Comment by brian-voong** [comment] 2022-10-14 15:45
> Ohhh, interesting! It sounds like changing `AnimationView` from a class to a typealias is source-compatible for existing Swift code but not for existing storyboards. Thanks for the info.
> 
> I don't think there's a fix for this on our side -- storyboards will just need to he updated to use `LottieAnimationView` instead of `AnimationView`. We're removing the old `AnimationView` declaration completely in Lottie 4.0 this month, which will hopefully change this cryptic error into something easier to understand (e.g. "no type named AnimationView").

I can confirm changing the element in our Storyboard from AnimationView to LottieAnimationView is no longer crashing for 3.5.0

**Comment by calda** [comment] 2022-12-06 23:37
We removed the `AnimationView` type in Lottie 4.0, so I assume this specific issue no longer happens. Thanks all for the report.

**Closed by calda** 2022-12-06 23:37 UTC
Labels: workaround
