### ISSUE TITLE
animation not appear 

### ISSUE THREAD

**Issue by alaadeego** [airbnb/lottie-ios#1037] opened 2019-09-26 00:55 UTC
hi all , i have issue i'm trying to add animation file , but its never appear i'v tried many way , and i test the file is valid , and tried many files .

lottie-ios (3.1.2)
- [] Swift

here the code
    @IBOutlet weak var animationView: UIView!
 
    override func viewDidLoad() {
        super.viewDidLoad()
        let starAnimation = Animation.named("wallet")
        let starAnimationView = AnimationView()
        starAnimationView.animation = starAnimation
        starAnimationView.contentMode = .scaleAspectFit
        starAnimationView.play()
        starAnimationView.translatesAutoresizingMaskIntoConstraints = false
        starAnimationView.frame = self.animationView.frame
 
        animationView.addSubview(starAnimationView)
    }

**Comment by SandraMarcelaHerreraArriaga** [comment] 2019-12-23 21:34
Hello :) 
I  test your code and I think that the following can work for you:
```
override func viewDidLoad() {
    super.viewDidLoad()
    let starAnimation = Animation.named("wallet")
    let starAnimationView = AnimationView()
    starAnimationView.animation = starAnimation
    starAnimationView.contentMode = .scaleAspectFit
    starAnimationView.play()
    starAnimationView.frame = self.animationView.bounds

    animationView.addSubview(starAnimationView)
}
```

if this not help you, maybe you must consider change the `animationView`  constraints

**Comment by calda** [comment] 2022-07-13 17:02
Closing since this seems like an iOS SDK question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:02 UTC
