### ISSUE TITLE
Error Stroke, KeyframeData, GradientStore

### ISSUE THREAD

**Issue by kidS2ran** [airbnb/lottie-ios#1704] opened 2022-08-08 10:34 UTC
Hi, I have a problem when using Lottie-ios 3.4.1

I'm clean, re-pod install but not resolve that issue.

## Which Version of Lottie are you using?

Lottie 3.4.1
![Screen Shot 2022-08-08 at 17 29 29](https://user-images.githubusercontent.com/6907632/183399075-467d644c-cb95-4f54-ab4b-22af7c448ac0.png)

![Screen Shot 20
![Screen Shot 2022-08-08 at 17 29 44](https://user-images.githubusercontent.com/6907632/183399082-6083d012-2fc9-4a60-9a9d-63c58dee13ab.png)
22-08-08 at 17 29 18](https://user-images.githubusercontent.com/6907632/183399063-838d7221-422d-490b-9c3a-4b06fc233649.png)

**Comment by kidS2ran** [comment] 2022-08-08 10:34
@calda  pls help me

**Comment by calda** [comment] 2022-08-08 13:49
This looks like a dupe of #1685. Could you share a sample project that reproduces this issue? The Lottie library builds correctly for me using Xcode 13.4.1. What Swift language version is your project using? (Lottie supports Swift 5.3+)

**Comment by calda** [comment] 2022-08-08 16:46
What Swift language version are you using? It looks like this could potentially be caused by a `try?` expression changing a `[DashElement]?` to a `[DashElement]??`. [SE-0230](https://github.com/apple/swift-evolution/blob/main/proposals/0230-flatten-optional-try.md) changed `try?` to not produce these types of double-wrapped optionals, but this was added in Swift 5.0. Is your project using the Swift 4 language mode? Lottie supports Swift 5.3+

**Comment by mavukz** [comment] 2022-08-08 19:31
I just resolved this by bumping swift version to 5. At project level it was pointing to 5 but target level 4.2

**Closed** 2022-08-08 19:33 UTC

**Comment by kidS2ran** [comment] 2022-08-10 02:51
> I just resolved this by bumping the swift version to 5. At the project level, it was pointing to 5 but target level 4.2

thanks! I fix it with pod script

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "lottie-ios"
      puts "Processing for set swiftcompiler language in SwiftSocket"
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
end
