### ISSUE TITLE
How to use lottie in collectionView Cell ? 

### ISSUE THREAD

**Issue by mustafacagripeker** [airbnb/lottie-ios#1310] opened 2021-01-24 00:16 UTC
Crashing Bug

<img width="1790" alt="Ekran Resmi 2021-01-24 03 15 22" src="https://user-images.githubusercontent.com/48365687/105617818-68674800-5df2-11eb-85b0-6fddbd4365bd.png">

<img width="1790" alt="Ekran Resmi 2021-01-24 03 15 55" src="https://user-images.githubusercontent.com/48365687/105617826-7c12ae80-5df2-11eb-8a69-2589265d3272.png">

**Comment by caioremedio** [comment] 2021-03-08 15:31
You are probably missing the module name below the Class Name, on the IB Panel.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/6145417/110341525-2e03e400-8009-11eb-81f5-dae0d43213fe.png">

**Comment by calda** [comment] 2022-07-13 17:37
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:37 UTC
