### ISSUE TITLE
`isAnimationPlaying` is always true when using `LottieLoopMode.playOnce`

### ISSUE THREAD

**Issue by artsimonyan23** [airbnb/lottie-ios#1681] opened 2022-07-30 14:59 UTC
After "LottieConfiguration.shared.renderingEngine = .automatic" the isAnimationPlaying every time is true.
After removing the seting of renderingEngine the animations work correctly.

## Which Version of Lottie are you using?
Lottie 3.4.1

**Comment by calda** [comment] 2022-07-30 17:13
Could you share some sample code or a sample project that reproduces this issue? Testing the example app in this repo, `isAnimationPlaying` correctly returns `false` when the animation is paused on a specific frame (as of #1608, from a few months ago).

**Comment by artsimonyan23** [comment] 2022-07-30 17:35
[TestLottie.zip](https://github.com/airbnb/lottie-ios/files/9226996/TestLottie.zip)

 "LottieConfiguration.shared.renderingEngine = .automatic" is written in the AppDelegate. Run the app and tap on the lottie picture. It will start playing. Tap again after it will finish. It will work only if you comment the line in the AppDelegate.

**Comment by calda** [comment] 2022-07-30 17:38
Thanks! Will take a look

**Comment by calda** [comment] 2022-07-30 21:43
I see, the problem is that `isAnimationPlaying` is still true after the animation ends when using `LottieLoopMode.playOnce`. Thanks for the report!

**Comment by calda** [comment] 2022-07-30 22:04
Fixed in #1682

**Closed** 2022-07-31 18:35 UTC
Labels: bug
