### ISSUE TITLE
How to Enter Number 0 to 9 and symbol like ? $ @ # ! ~  * &  ./  < { [ ( 

### ISSUE THREAD

**Issue by hardikk** [airbnb/lottie-ios#166] opened 2017-03-06 13:34 UTC
Hi team , 

You done great when we want enter char. (A to Z ).
But kindly guide what when user want to enter Number 0 to 9 and symbol like ? $ @ # ! ~  * &  ./  < { [ ( .

For example .

Hi Jack happy Birthday! You won Lucky(TM) lottery worth $200.99 from DreamWorld(R)  .kindly collect it kindly bring you ID documents with original copy Today before 10:59:59 from our office : www.dreamworld.com/office/  or  info@dreamworld.com call . 1800 180 XXXX 

how your libs are useful in it how to use it ?  

AS you have shared A to Z.json only .

Kindly reply ASAP .

Many many Thanks in advanced .

**Comment by gpeal** [comment] 2017-03-10 17:14
Dupe of #165

**Closed by gpeal** 2017-03-10 17:14 UTC
