### ISSUE TITLE
Animations presented badly on 3.4.0

### ISSUE THREAD

**Issue by RoyMChen** [airbnb/lottie-ios#1664] opened 2022-07-26 11:08 UTC
## Which Version of Lottie are you using?

Expected Behavior - recorded in Lottie 3.3.0
Actual Behavior - recorded in Lottie 3.4.0

## Expected Behavior 

https://user-images.githubusercontent.com/110029256/180990327-dc87b209-179a-4e7a-ae16-6d47e7ec792e.mp4

https://user-images.githubusercontent.com/110029256/180990335-e6e42069-4cec-4d5f-ae67-b6a96d1ea9a5.mp4

## Actual Behavior

https://user-images.githubusercontent.com/110029256/180988905-98279088-24f3-4e9c-ba79-9b0726f24e06.mp4

https://user-images.githubusercontent.com/110029256/180988934-712dddbb-5bae-482f-86d1-4994cbedb1e5.mp4

## Animation JSON

[Archive.zip](https://github.com/airbnb/lottie-ios/files/9189159/Archive.zip)

**Comment by calda** [comment] 2022-07-26 18:23
What rendering engine option are you using? Are you setting custom value providers to customize the colors of the animation? Could you share the source code for this, or ideally a sample project that reproduces the issue if possible?

When I look at the animation json files you shared on lottiefiles.com and compare them to what I see in the sample iOS app, the animation looks identical as far as I can tell.

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/1811727/181082561-dca39fd9-d7ea-41f2-b718-31181aaa735c.png">

**Comment by RoyMChen** [comment] 2022-07-31 08:26
I used mainThread as the render engine option.
This is the source code for the first animation (the second one has the same logic): 

        let animation = Animation.named("AR_Onboarding_Radar")
        self.animationView.animation = animation
        self.animationView.contentMode = .scaleAspectFit
        self.animationView.loopMode = .loop
        self.animationView.backgroundBehavior = .pauseAndRestore
        let color = UIColor.black **
        let colorValue = ColorValueProvider(color.lottieColorValue)
        let keypath = AnimationKeypath(keypath: "**.base_color.**.Color")
        self.animationView.setValueProvider(colorValue, keypath: keypath)
        self.animationView.play()

** here I use dynamic color for light/ dark mode (other than UIColor.black)

**Comment by calda** [comment] 2022-07-31 16:07
It looks like this is the same issue as #1683, and is fixed by https://github.com/airbnb/lottie-ios/pull/1684. Thanks for the report!

**Closed** 2022-08-01 00:28 UTC
Labels: bug
