### ISSUE TITLE
Crash on CGPoint.interpolate

### ISSUE THREAD

**Issue by luan-sala** [airbnb/lottie-ios#934] opened 2019-06-03 20:18 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [ ] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [ ] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [ ] Objective-C

## Animation JSON

---

Crash log
-

> Crashed: WebThread
0  Lottie                         0x11ef652 specialized CGPoint.interpolate(_:outTangent:inTangent:amount:maxIterations:samples:accuracy:) (<compiler-generated>)
1  Lottie                         0x11ef50f specialized CGPoint.interpolate(_:outTangent:inTangent:amount:maxIterations:samples:accuracy:) (<compiler-generated>)
2  Lottie                         0x11dae8f specialized Vector3D.interpolateTo(_:amount:spatialOutTangent:spatialInTangent:) (<compiler-generated>)
3  Lottie                         0x11da75f protocol witness for Interpolatable.interpolateTo(_:amount:spatialOutTangent:spatialInTangent:) in conformance Vector3D (<compiler-generated>)
4  Lottie                         0x11e14fd Keyframe.interpolate(_:progress:) (KeyframeExtensions.swift:40)
5  Lottie                         0x11e38bd KeyframeInterpolator.value(frame:) (KeyframeInterpolator.swift:83)
6  Lottie                         0x11e4d67 protocol witness for AnyValueProvider.value(frame:) in conformance KeyframeInterpolator<A> (<compiler-generated>)
7  Lottie                         0x11f08cb NodeProperty.update(frame:) (NodeProperty.swift:43)
8  Lottie                         0x11f0959 protocol witness for AnyNodeProperty.update(frame:) in conformance NodeProperty<A> (<compiler-generated>)
9  Lottie                         0x11f0d0b specialized NodePropertyMap.updateNodeProperties(frame:) (<compiler-generated>)
10 Lottie                         0x11b976b specialized AnimatorNode.updateContents(_:forceLocalUpdate:) (AnimatorNode.swift:145)
11 Lottie                         0x11c3d6d CompositionLayer.displayWithFrame(frame:forceUpdates:) (AnimatorNode.swift:157)
12 Lottie                         0x11ad359 AnimationContainer.display() (AnimationContainer.swift:163)
13 Lottie                         0x11ad407 @objc AnimationContainer.display() (<compiler-generated>)
14 QuartzCore                     0x1ffbfb9f CA::Layer::display_if_needed(CA::Transaction*) + 208
15 QuartzCore                     0x1ffbfc0d CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
16 QuartzCore                     0x1ff4e839 CA::Context::commit_transaction(CA::Transaction*) + 320
17 QuartzCore                     0x1ff6cfdb CA::Transaction::commit() + 578
18 QuartzCore                     0x1ff6db2f CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 162
19 CoreFoundation                 0x1d0ff803 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 20
20 CoreFoundation                 0x1d0fda55 __CFRunLoopDoObservers + 282
21 CoreFoundation                 0x1d0fe017 __CFRunLoopRun + 1358
22 CoreFoundation                 0x1d0511af CFRunLoopRunSpecific + 470
23 CoreFoundation                 0x1d050fd1 CFRunLoopRunInMode + 104
24 WebCore                        0x21275ce3 <redacted> + 426
25 libsystem_pthread.dylib        0x1c9c893b _pthread_body + 216
26 libsystem_pthread.dylib        0x1c9c885d _pthread_start + 234
27 libsystem_pthread.dylib        0x1c9c6468 thread_start + 8

I don`t have many details about the crash. Sometimes the crash occur with the users, sometimes not.
In the older version of Lottie (v2.5.2), all works beautiful and wonderful.

**Comment by gilmarcsf** [comment] 2019-06-11 23:56
This crash is happening on iOS 9.3.5 and iOS 10.3.3

**Comment by prince-kumar** [comment] 2019-10-16 05:07
The issue is very recurring on 9.3.5 and 9.3.6, do we have update on this

**Comment by rk85097** [comment] 2019-10-30 07:50
Hi, any news? I am experiecning this issue as well.

**Comment by buba447** [comment] 2019-11-26 16:55
Should be fixed in latest release

**Closed by buba447** 2019-11-26 16:55 UTC
