### ISSUE TITLE
App crashes when using IBOutlet

### ISSUE THREAD

**Issue by rohdester** [airbnb/lottie-ios#840] opened 2019-04-01 13:38 UTC
## This issue is a:
- [X] Crashing Bug
- [X] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.3

## What Platform are you on? 

- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 
I expect that the animation worked as it did in pre 3.x versions.

## Actual Behavior
The app crashes.

## Code Example
I have code like this:

```
import UIKit
import Lottie

class BlockForNonProViewController: UIViewController {
    @IBOutlet weak var animationContainer: AnimationView!
    @IBOutlet weak var okButton: UIButton!

    var shouldHideOkButton: Bool = true

    override func viewDidLoad() {
        super.viewDidLoad()
        let animation = Animation.named("blocked-animation")
        animationContainer.animation = animation
        animationContainer.contentMode = .scaleAspectFit
        animationContainer.loopMode = .loop
        animationContainer.play()
    }

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        okButton.isHidden = shouldHideOkButton
    }

    @IBAction func okButtonTapped(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
}
```

The app crashes on the line `animationContainer.animation = animation` with an "unrecognized selector sent to instance". It seems the view controller itself is sent the selector removeFromLayer which makes no sense on a view controller.

The animation view is an IBOutlet which perhaps is what version 3.x can't handle?

**Comment by Andreas409** [comment] 2019-04-01 15:27
possible duplicate of [this](https://github.com/airbnb/lottie-ios/issues/826)

**Comment by buba447** [comment] 2019-04-01 16:56
Seems like a duplicate. Setting the module field to `Lottie` should fix this problem. Its a strange issue with cocoapods and swift that it doesnt autofill. Im looking into that.

**Closed by buba447** 2019-04-01 16:56 UTC
