### ISSUE TITLE
TwitterHeartButton.json marker

### ISSUE THREAD

**Issue by maciaspeter** [airbnb/lottie-ios#855] opened 2019-04-09 14:04 UTC
I don't see the aep file for twitter icon button in the aep files. I'm primarily looking for the markers to understand how the AnimatedButton works. 

## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [X] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 2.52 - wanted to understand how lottie 3.0.2 works before I upgrade Lottie.

## What Platform are you on? 

- [X] MacOS
- [] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

**Comment by calda** [comment] 2022-07-13 17:15
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:15 UTC
