### ISSUE TITLE
3D Layer from AE is not supported?

### ISSUE THREAD

**Issue by Goozoon** [airbnb/lottie-ios#809] opened 2019-03-21 14:16 UTC
I wanted to add animation made as 3D Layer in AE. When i render in Bodymovin i can see the animation. Once it is included in iOS project - i see a static image.

Related to:
https://github.com/airbnb/lottie-web/issues/1538

AE project: https://we.tl/t-LRKE7ZpXcw

Thank you

**Comment by buba447** [comment] 2019-03-21 14:50
This is a duplicate of https://github.com/airbnb/lottie-ios/issues/710

Closing this issue and you can follow along over there.

**Closed by buba447** 2019-03-21 14:50 UTC
