### ISSUE TITLE
Animations not working Lottie 3.0.1 & 3.0.2

### ISSUE THREAD

**Issue by Patrashkov** [airbnb/lottie-ios#819] opened 2019-03-22 10:13 UTC
## Lottie-iOS Issue
Animations that worked fine in Lottie 2.5.2 do not work in Lottie 3.0.1 & 3.0.2
In your Test project my json files didn't work, but you json files work fine. 
I have sent your example project with my json files.
Please, help me to resolve this issue.

## This issue is a:
- Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.0.2

## What Platform are you on? 
- iOS

## What Language are you in?
- Swift

## Animation JSON
Sent

**Comment by buba447** [comment] 2019-03-22 12:54
I see that your animation uses image references! The file you sent me didnt include images reference, but once i loaded up some dummy images using an `AnimationImageProvider` the animation worked just fine. So the problem is that Lottie can't find the images for you animation.

The way image handling works changed a bit with Lottie 3.0. Lottie loads images using an image handler `animationView.imageProvider`. The default value for this image provider tries to find and load the images from the main bundle. Lottie come with two different image providers by default and you can make your own. The two defaults are `BundleImageProvider` and `FilepathImageProvider`. Bundle will load from a specified bundle, and filepath will load images from a filepath. 

So if you just create an image provider using one of the classes above and point it to your images, your animation should work just fine!

Read more about it here: https://github.com/airbnb/lottie-ios#image-provider

Im going to close this, but feel free to ask more questions here or reopen it if you have anymore troubles.

**Closed by buba447** 2019-03-22 12:54 UTC

**Comment by Patrashkov** [comment] 2019-03-22 15:36
Thank you for your answer!
But in my example image collection is in folder "Images.xcassets". When I
use just "main bundle" for init  BundleImageProvider, it can't find any
images, because this path is nil.
Can you explain me what I do incorrect.

Thank you!

пт, 22 мар. 2019 г. в 14:54, Brandon Withrow <notifications@github.com>:
