### ISSUE TITLE
Troubleshooting Lottie Integration Errors in GitHub Actions CI/CD Pipeline

### ISSUE THREAD

**Issue by mBellar** [airbnb/lottie-ios#2333] opened 2024-03-11 12:16 UTC
### Discussed in https://github.com/airbnb/lottie-ios/discussions/2332

<div type='discussions-op-text'>

<sup>Originally posted by **mBellar** March 11, 2024</sup>
Hello Everyone, 

I am encountering difficulties with integrating Lottie into our CI/CD pipeline on GitHub Actions. I am using the lottie-spm extension. When running our workflow, I encounter errors indicating that it cannot find the 'LottieAnimation' and 'LottieAnimationView' types within the scope. These errors only occur on machines hosted by GitHub Actions, while execution on our local machines proceeds without any issues.

![Screenshot 2024-03-11 at 10 28 30](https://github.com/airbnb/lottie-ios/assets/147486707/ae9842a5-1388-4487-9048-6fa867e9c9cc)

However, when attempting to compile the application using SDK 'iphoneos17.2' with Fastlane, I encounter a similar error:

![Screenshot 2024-03-11 at 12 03 42](https://github.com/airbnb/lottie-ios/assets/147486707/0cf3546d-6f8e-45f4-9b5b-d75663ad7011)

Then, upon changing the SDK to 'iphoneos17.0', I received this error:

`xcodebuild: error: SDK "iphoneos17.0" could not be found.`

My GitHub Actions workflow is currently configured to run on macOS 13.
I use as environment : 
- Xcode 15.0.1
- SDK Name : iphoneos17.2.

Could you help me resolve these errors related to Lottie and understand how to properly specify the SDK in Fastlane to solve the compatibility issue?

Thank you very much for your help.

Best regards

</div>

**Comment by mBellar** [comment] 2024-03-11 15:26
@calda

**Comment by calda** [comment] 2024-03-11 16:19
Closing as duplicate of https://github.com/airbnb/lottie-ios/discussions/2332 -- this is better as a discussion rather than an issue

**Closed by calda** 2024-03-11 16:19 UTC
