### ISSUE TITLE
CollectionView scrolling behaviour

### ISSUE THREAD

**Issue by alextudge** [airbnb/lottie-ios#852] opened 2019-04-08 10:22 UTC
## Check these before submitting:
- [/] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [/] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [/] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [/] iOS

## What Language are you in?
- [/] Swift
- [] Objective-C

## Expected Behavior 

When adding lottie into a collectionView (one lottie per full screen cell) the horizontal transition should remain smooth.

## Actual Behavior

When scrolling through a collection view (one lottie per full screen cell) the horizontal transition is jumpy and generates the following console output:
2019-04-08 11:15:45.705072+0100 MoneyBox[6939:161528] [UIWorkIntervalTiming] workIntervalStart: startTimestamp > targetTimestamp; rolling forward by 0.483333

Converting the lottie view to UIView's confirms that normal behaviour and no console output is generated when lottie isn't present

## Code Example

Each cell's lottie is played on cell appearance, and has its currentProgress set to 0 as the cell disappears. It is set to playOnce.

**Comment by lucasmpaim** [comment] 2019-10-09 19:22
+1 Same problem with UITableView, when play an animation the scroll not remain smooth

**Comment by tundsD53** [comment] 2020-01-02 21:39
I've downgraded to version 2.5.3 in Obj-C and the scrolling seems to be smoother, so this is definitely related to Swift and the issue tagged above.

**Comment by calda** [comment] 2022-07-13 17:16
Closing since this seems like a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:16 UTC
