### ISSUE TITLE
Linear position keyframes are eased

### ISSUE THREAD

**Issue by nlogioco** [airbnb/lottie-ios#60] opened 2017-02-08 19:04 UTC
So I'm doing a position transform on a layer and in AE it runs linearly. When I run it on device (iOS) it looks like it runs linearly until the last 80% of the animation and then it slows down. 

Any reason why?

**Comment by therealsalih** [comment] 2017-02-08 21:11
Can you send the AE file so we can test it out?

**Comment by lawsonshanks** [comment] 2017-02-08 21:53
@therealsalih Here is the AE file. Animation works fine in AE and the bodymovin preview, but seems to have a lag in the first y-axis position transform when run through Lotti.
[drop-rotate.aep.zip](https://github.com/airbnb/lottie-ios/files/762046/drop-rotate.aep.zip)

**Comment by therealsalih** [comment] 2017-02-09 18:51
Hi @nlogioco and @lawsonshanks I can see what the issue is here. it looks like there an issue with linear position keyframes. they look like they are easing even though they are linear. We will look into this ASAP! Thanks!

**Comment by buba447** [comment] 2017-02-24 18:41
Finally looked into this! So its not actually the timing information thats causing the error, its the control point on the path. Its a linear path but it has a control point on the end. This is confusing Core Animation for some reason. It seems that core animation doesn't solely depend on timing functions for easing unfortunately. To fix this we will have to write a custom interpolator. 

For now a quick fix is to just remove the control point from your path animation 

<img width="194" alt="screen shot 2017-02-24 at 10 41 19 am" src="https://cloud.githubusercontent.com/assets/1163980/23316068/ce2a3332-fa7d-11e6-86ca-a749ea48b93f.png">

**Comment by catlan** [comment] 2017-08-01 09:46
@buba447 Thx! 

We run into this issue with the first animation we created. May I suggest to add this as know issue in the readme.

**Comment by buba447** [comment] 2017-08-02 22:28
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Comment by YoshyB** [comment] 2018-09-19 14:16
@buba447 Is there any news on this particular case?

**Comment by buba447** [comment] 2019-03-17 17:10
Finally found a fix for this!
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Closed by buba447** 2019-03-17 17:10 UTC
Labels: bug
