### ISSUE TITLE
App crashed when call NSBundle.getAnimationData

### ISSUE THREAD

**Issue by peter-Kings** [airbnb/lottie-ios#1607] opened 2022-05-25 12:15 UTC
App will crash After HomeViewController viewDidLoad Initialize LottieRefreshHeader and add an AnimationView.
I provided the crash and json file at the end.
I see the stacktrace, call getAnimationData then crashed.
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [ ] Non-Crashing Bug (Visual or otherwise)
- [X] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0

## What Platform are you on? 

- [ ] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [ ] Objective-C

## Expected Behavior 

Non-crash
## Actual Behavior

App crash when launch and AnimationView init
## Code Example
class LottieRefreshHeader: MJRefreshStateHeader {
    var lottieAnimationView: AnimationView!
    override func prepare() {
        super.prepare()
        lottieAnimationView = AnimationView(name: "pullrefresh", bundle: Bundle.lottieBundle)
        addSubview(lottieAnimationView)
    }
}

extension Bundle {
    class var lottieBundle: Bundle {
        let url = Bundle.main.url(forResource: "XXX", withExtension: "bundle")!
        let bundle = Bundle(url: url)!
        return bundle
    }
}
## Animation JSON

[Lottie_animation.json.zip](https://github.com/airbnb/lottie-ios/files/8770805/Lottie_animation.json.zip)
[2022-05-23_08-50-36.7386_+0800-e0f702773c2b519dbcb5fd01905fde0091cd94da.crash.zip](https://github.com/airbnb/lottie-ios/files/8770821/2022-05-23_08-50-36.7386_%2B0800-e0f702773c2b519dbcb5fd01905fde0091cd94da.crash.zip)

**Comment by calda** [comment] 2022-07-13 17:54
Closing since this looks like an iOS SDK question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:54 UTC
