### ISSUE TITLE
animation stop after enter background

### ISSUE THREAD

**Issue by GeekSprite** [airbnb/lottie-ios#481] opened 2017-11-10 09:05 UTC
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [ ] Updated to the latest (2.1.3) version of Lottie
- [ ] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [ ] This issue isnt related to another open issue

## This issue is a
- [ ] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [ ] iOS (Specify Platform Version)

## Expected Behavior 
(Screenshots encouraged)

## Actual Behavior
(Screenshots encouraged)

## Animation JSON
Adding the animation JSON helps us debug the issue faster!

**Comment by GeekSprite** [comment] 2017-11-10 09:06
I set loopAnimation to YES   ,it works fine frist,but when I pressed the home button,and then back the app, the animation stopped

**Comment by DarthMike** [comment] 2017-11-21 16:57
+1 

I think it would be nice to have this as a controllable flag, so the view could handle the pause/resume if it was playing when entering background and becoming active.

BTW thanks for a great project!

**Comment by EZIOoooo** [comment] 2017-11-23 09:05
+1
I think it is base on Core animation, so .... how to fix it?

**Comment by mchangxe** [comment] 2017-11-23 09:47
seeing this same problem... Added an animation as subview to an UIView object, loop is on yes but the animation disappears after a few seconds...

**Comment by GeekSprite** [comment] 2017-12-04 07:35
@EZIOoooo In Core Animation ,set CAAnimation  removeOnCompletion = NO; can solve this problem, but this don't work for lottie...

**Comment by wucanqi** [comment] 2017-12-12 03:21
+1 the same problem , emmmmmmmm, so .... somebody tell how to fix plz......

**Comment by Brsoyan** [comment] 2017-12-15 12:45
In viewdidappear you can check isAnimationPlaying property. If Its false call [animationView play]

**Comment by devnull0000** [comment] 2017-12-21 17:27
+1 the same problem

**Comment by GeekSprite** [comment] 2018-01-05 09:00
@Brsoyan  It wont't work, come to foreground, UIViewController will not call viewdidappear,
but you can observe system Notification --UIApplicationWillEnterForegroundNotification  ,but it is kind of stupid.

**Comment by ezequieloliveiralima** [comment] 2018-01-20 14:44
I have the same problem, and I have downgraded to V 2.0.3:

pod 'lottie-ios', '2.0.3'

Worked for me...

**Comment by Osama92** [comment] 2018-02-12 14:05
Just implemented **viewDidLayoutSubview() method**, put the animation within the method and it works fine. Thank you!

**Comment by Agenric** [comment] 2018-03-09 03:37
I tried to hook `play` method in the category's `load` method and added a listener to `UIApplicationDidEnterBackgroundNotification` and `UIApplicationDidBecomeActiveNotification` notifications to solve this problem.
But I don’t know if this will have any risk, or do you have any suggestions?

**Comment by hezhk3** [comment] 2018-04-08 01:47
Just observe UIApplicationWillEnterForegroundNotification in your view controller
```
[[NSNotificationCenter defaultCenter] addObserverForName:UIApplicationWillEnterForegroundNotification object:nil queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification * _Nonnull note) {
    if (![animationView isAnimationPlaying]) {
                [animationView play];
            }
}];
```

**Comment by AdhamAliAhmed** [comment] 2018-06-28 02:49
Hey!
I had the same problem which is the animation disappear when i leave the page where the animation is located and come back to it later
i solved it although i work on Lottie.Forms but the solution is generic it gonna work for each one of you.
there is some event fired when the animation page loads right regardless your platform is right?
you subscribe to this event and do this:
remove the animation view implemented earlier 
insert a new animation object within the same place

it's not  very friendly to the performance but it woks since there is no official solution from Lottie themselves

**Comment by Claus79** [comment] 2018-07-04 23:57
Have you tried to program a simple delay? My animation was stopping after the first play, then I did:
```
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) { 
            // Your code with delay
            self.animatedView.loopAnimation = true
            self.animatedView.play()
        }
```
and it started working. Hope it helps!

**Comment by zapjonny** [comment] 2018-07-06 10:50
IMHO This should definitely be a feature of Lottie. It was always a pain in the a££ to fix the UIKit/calayer animations on foreground. It was always one of the weaknesses. Game rendering engines etc do not have this problem.

**Comment by zapjonny** [comment] 2018-07-06 10:53
At least it should be a feature that is by default on (auto pause in bg, resume on fg) that could be toggled off as needed.

**Comment by taeger** [comment] 2018-08-15 10:03
for me, this worked:

```
override func viewDidLoad() {
        super.viewDidLoad()
        NotificationCenter.default.addObserver(self, selector: #selector(restartAnimation), name: NSNotification.Name.UIApplicationWillEnterForeground, object: nil)
}

@objc func restartAnimation() {
        animation.play()
}
```

**Comment by zapjonny** [comment] 2018-08-15 10:09
Yes sure it works - of course. thanks.

**Comment by DarthMike** [comment] 2018-09-18 10:45
We can all do that @luyinuo. The point of this issue is to get it changed in the library, not having to workaround this. And if it doesn't work like this by design, to know why...

**Comment by jeffMeador** [comment] 2018-10-19 13:19
Recommending swizzling shouldn't be so casual. 

Fortunately, it looks like a fix was put in place for this by @buba447 in 2.5.1 and can probably mark this as fixed. Thanks buba!

**Comment by BCWoodard** [comment] 2018-10-25 20:56
Updated to the most recent version on 10/25/18 and this has been corrected. Thanks @buba447 !

**Comment by Umar3x** [comment] 2018-10-26 00:49
Hello all. What is exactly the root cause of that? I'm using xamarin forms and I have this issue of both platforms ios and Android but the animation literally disappears sometimes and come back or not but there is nothing in the logs.

**Comment by charles161** [comment] 2019-01-07 14:35
cool

**Comment by buba447** [comment] 2019-03-17 17:04
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Closed by buba447** 2019-03-17 17:04 UTC

**Comment by levantAJ** [comment] 2019-05-05 09:48
Seem we have this to pause in background and restart when it reach foreground `animationView.backgroundBehavior = .pauseAndRestore`

**Comment by dor4emon** [comment] 2019-07-01 05:15
thanks @levantAJ , worked a charm

**Comment by vivekjohn** [comment] 2021-04-04 14:45
One of the best solution:

1. Create a notifier when the app goes to the background for pause and when back to foreground

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let notificationCenter = NotificationCenter.default
        notificationCenter.addObserver(self, selector: #selector(appMovedToBackground), name: UIApplication.willResignActiveNotification, object: nil)
        notificationCenter.addObserver(self, selector: #selector(appBecomeActive), name: UIApplication.didBecomeActiveNotification, object: nil)

        animationView = .init(name: "lang")
        animationView!.frame = CGRect(x: 20, y: 100, width: 50, height: 50)
        animationView!.contentMode = .scaleAspectFit
        animationView!.loopMode = .loop
        animationView!.animationSpeed = 0.5
        view.addSubview(animationView!)
        animationView!.play()
    }

2. This will invoke notification methods when the app moves to background and foreground

    @objc func appMovedToBackground() {
           print("App moved to background!")

        animationView!.removeFromSuperview()
        }

    @objc func appBecomeActive() {
           print("App become active")
        //animationView!.play()

        animationView = .init(name: "lang")
        animationView!.frame = CGRect(x: 20, y: 100, width: 50, height: 50)
        animationView!.contentMode = .scaleAspectFit
        animationView!.loopMode = .loop
        animationView!.animationSpeed = 0.5
        view.addSubview(animationView!)
        animationView!.play()
        }

This will solve your problem....... For sure

**Comment by jeffMeador** [comment] 2021-04-08 19:57
@vivekjohn this feature was added to the library a few years ago as shown in some of the comments here. The flag is `animationView.backgroundBehavior = .pauseAndRestore`. I think your comment will just confuse people looking for an answer and we wouldn't want beginners copying all those force unwraps either.

**Comment by lyandy** [comment] 2022-01-04 08:29
> Seem we have this to pause in background and restart when it reach foreground `animationView.backgroundBehavior = .pauseAndRestore`

works for me. tks

**Comment by AbdelrahmanAbdelwahab** [comment] 2022-08-03 09:01
> 

 NotificationCenter.default.addObserver(self, selector: #selector(restartAnimation), name: UIApplication.willEnterForegroundNotification, object: nil)

**Comment by rishavjnv12** [comment] 2023-01-02 10:40
Thanks @jeffMeador. Worked for me
