### ISSUE TITLE
Animation gets blurry when implemented

### ISSUE THREAD

**Issue by Mannnny** [airbnb/lottie-ios#1279] opened 2020-10-27 17:01 UTC
Hi,

I've created an animation using pngs, some of which are pixel fonts. Everything was fine in after effects, the demo html file was fine as well. But whenever my engineers implement it, the pixel fonts get blurry, and the pixels start losing the paddings.

Is there a setting I missed in lottie? or is it a dev side issue?

preview in html:
<img width="285" alt="Screen Shot 2020-10-27 at 9 23 46 AM" src="https://user-images.githubusercontent.com/22826140/97335624-497d0800-183b-11eb-9090-0dc057f5e62b.png">

Implemented in iOS:
<img width="304" alt="Screen Shot 2020-10-27 at 9 23 10 AM" src="https://user-images.githubusercontent.com/22826140/97335666-54d03380-183b-11eb-957a-fd69d972f0d8.png">

thanks!

**Comment by Bjorninn1** [comment] 2021-05-04 19:24
I have noticed this happening when a layer has a gradient. Try selecting a layer with this blurring problem inside Illustrator or in the software you use for the drawing. Then change the color of the layer to a non-gradient color. After creating a new lottie-file it should work in iOS. This was at least the problem in my case and solved it. Don´t know why this happens though since gradient should be supported according to: https://github.com/airbnb/lottie/blob/master/supported-features.md and I am using the newest pod for lottie (3.2.2)

**Comment by absolute-heike** [comment] 2021-05-07 20:26
@Bjorninn1 We fixed some performance issues in 3.2.2 that seem to have broken gradient rendering.

If you didn't have any performance issues before I suggest to downgrade to 3.2.1 until it is fixed.

**Comment by vincefried** [comment] 2021-09-01 11:25
Hi! I also stumbled across the exact same problem with 3.2.3 and downgrading to 3.2.1 fixed it. Are there any plans to resolve the issue in the near future?

**Comment by calda** [comment] 2022-07-06 21:32
I believe this was fixed by by #1436 / is a dupe of #1407

**Closed by calda** 2022-07-06 21:32 UTC
