### ISSUE TITLE
AnimatedButton via storyboard doesnt work

### ISSUE THREAD

**Issue by adithimev** [airbnb/lottie-ios#955] opened 2019-06-19 11:00 UTC
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [✓] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [✓] iOS

## What Language are you in?
- [✓] Swift
- [] Objective-C

## Code Example

Im trying to add an animatedbutton via storyboard. It doesnt allow me to add animatedbutton in custom class name, so added it in properties alone 
    @IBOutlet var button1: AnimatedButton!

i get a crash while adding
button1.animation = Animation.named("animationfile")

**Comment by ctreffs** [comment] 2019-06-21 09:04
Hi there, 
I had a similar issue with loading an animation with a storyboard component.
The problem seems to be due to the interface builder not using the main bundle as you would expect (similar to problems with image literals).

Fixed it by using this snippet:

```swift
public extension Animation {
    static func namedStoryboardCompatible(_ name: String,
                                          bundle: Bundle = Bundle.main,
                                          subdirectory: String? = nil,
                                          animationCache: AnimationCacheProvider? = nil) -> Animation? {
        
        #if TARGET_INTERFACE_BUILDER
        var bundle = bundle
        bundle = Bundle.allBundles.first(where: { $0.bundleIdentifier?.contains("<the_bundle_where_your_animation_file_is_located>") ?? false }) ?? Bundle.main
        #endif
        
        return self.named(name, bundle: bundle, subdirectory: subdirectory, animationCache: animationCache)
    }
}
```

Hope this helps.

**Comment by adithimev** [comment] 2019-06-24 07:45
Can you give me some more details on this..

**Comment by ctreffs** [comment] 2019-06-24 09:35
If the Interface Builder is building it's preview `Bundle.main` is not the same bundle for finding your resources as it is while running the App. This is due to Interface Builder using its own (hidden) target to build the interface for preview. This leads to look up problems for resources that are found via `Bundle.main`.
See this SO post for an in-depth explanation: https://stackoverflow.com/a/41302895

Hope I could help.

**Comment by adithimev** [comment] 2019-06-24 09:38
ok.. So should i still make the button custom class as AnimatedButton.. ?

How does the loading button work then?

**Comment by ctreffs** [comment] 2019-06-24 09:45
Your problem seems to be loading the animation - not the button itself. 
Try loading the animation with the `TARGET_INTERFACE_BUILDER` macro extension and you should be fine.

**Comment by buba447** [comment] 2019-07-11 14:00
Make sure you set the module name as well. Sometimes xcode does not populate that field.

<img width="219" alt="Screen Shot 2019-07-11 at 9 00 22 AM" src="https://user-images.githubusercontent.com/1163980/61057154-52359a80-a3ba-11e9-8631-2e8dbebbaca5.png">

**Comment by adithimev** [comment] 2019-07-11 14:03
It doesn’t allow me set the module name on storyboard.. The moment I set it, it disappears.

Regards,

Adithi Bolar
iOS Developer

[signature_2033429520]

Unit 501, Level 5, Building #2,
Emaar Square, Downtown Dubai,
Dubai, UAE
Mob: +971528689081
www.intelligentb.com<http://www.intelligentb.com/>

**Comment by calda** [comment] 2022-07-13 17:12
Closing since this seems like an iOS SDK question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:12 UTC
