### ISSUE TITLE
animation is playing in the first view only

### ISSUE THREAD

**Issue by ramymabrouk** [airbnb/lottie-ios#405] opened 2017-09-05 06:33 UTC
## Lottie-ios Issue
Hello! Sorry you are having an Issue! Please help us make Lottie better by filling everything below out with as much information as you can so we can try to reproduce and fix the issue!

## Check these before submitting:
- [X] Updated to the latest (2.1.3) version of Lottie
- [X] The issue doesnt involve and [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#currently-unsupported-after-effects-features)
- [X] This issue isnt related to another open issue

## This issue is a
- [X] Non-Crashing (Visual or otherwise) Bug
- [ ] Crashing Bug
- [ ] Feature Request
- [ ] Regression (Something that once worked doesnt work anymore)

## What Platform are you on? 
- [ ] MacOS (Specify Platform Version)
- [X] iOS (10.3.3)

## Expected Behavior 
the animation plays

## Actual Behavior
the animation does not play

## Code Example
        let av = LOTAnimationView(name: "outline_user")
        av.frame = CGRect(x: 8, y: 6, width: 30, height: 30)

        av.setValue(themeColor, forKeypath: "UserIcon contornos.Grupo 1.Trazo 1.Color", atFrame: 0)
        av.setValue(themeColor, forKeypath: "UserIcon contornos.Grupo 2.Trazo 1.Color", atFrame: 0)
        nameContainerView.addSubview(av)
        av.play()
## Animation JSON
Adding the animation JSON helps us debug the issue faster!

##########
Hi,
the animation is played well in my first view only, other views shows without the animation run, I do not get any error or crash in the app, it just does not start, I have enabled the debug logging and got the logging below
2017-09-05 08:10:07.548 VeeCeleb[8575:144729] -------------------- ------------------------------- --------------------
2017-09-05 08:10:07.590 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Transform.Scale
2017-09-05 08:10:07.590 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Transform.Position
2017-09-05 08:10:07.591 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Transform.Anchor Point
2017-09-05 08:10:07.591 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Transform.Rotation
2017-09-05 08:10:07.591 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Transform.Opacity
2017-09-05 08:10:07.591 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Trazo 1.Color
2017-09-05 08:10:07.592 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Trazo 1.Opacity
2017-09-05 08:10:07.592 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Trazo 1.Stroke Width
2017-09-05 08:10:07.592 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Recortar trazados 1.Start
2017-09-05 08:10:07.592 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Recortar trazados 1.End
2017-09-05 08:10:07.593 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Recortar trazados 1.Offset
2017-09-05 08:10:07.593 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 2.Trazado 1.Path
2017-09-05 08:10:07.593 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Transform.Scale
2017-09-05 08:10:07.593 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Transform.Position
2017-09-05 08:10:07.593 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Transform.Anchor Point
2017-09-05 08:10:07.594 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Transform.Rotation
2017-09-05 08:10:07.594 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Transform.Opacity
2017-09-05 08:10:07.594 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Trazo 1.Color
2017-09-05 08:10:07.594 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Trazo 1.Opacity
2017-09-05 08:10:07.595 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Trazo 1.Stroke Width
2017-09-05 08:10:07.595 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Recortar trazados 1.Start
2017-09-05 08:10:07.595 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Recortar trazados 1.End
2017-09-05 08:10:07.595 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Recortar trazados 1.Offset
2017-09-05 08:10:07.595 VeeCeleb[8575:144729] |UserIcon contornos.Grupo 1.Trazado 1.Path
2017-09-05 08:10:07.596 VeeCeleb[8575:144729] -------------------- Composition Displaying Frame 0 --------------------
2017-09-05 08:10:07.596 VeeCeleb[8575:144729] View <LOTCompositionContainer: 0x60800012d700> Displaying Frame 0
2017-09-05 08:10:07.596 VeeCeleb[8575:144729] View <LOTLayerContainer: 0x608000106ae0> Displaying Frame 0
2017-09-05 08:10:07.597 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959552 Trazo 1 Checking for update
2017-09-05 08:10:07.597 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959552 Trazo 1 Performing update
2017-09-05 08:10:07.597 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872646272 Trazado 1 Checking for update
2017-09-05 08:10:07.597 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872646272 Trazado 1 Performing update
2017-09-05 08:10:07.598 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873015296 Grupo 2 Checking for update
2017-09-05 08:10:07.598 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873015296 Grupo 2 Performing update
2017-09-05 08:10:07.598 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959440 Trazo 1 Checking for update
2017-09-05 08:10:07.598 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959440 Trazo 1 Performing update
2017-09-05 08:10:07.598 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872644432 Trazado 1 Checking for update
2017-09-05 08:10:07.599 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872644432 Trazado 1 Performing update
2017-09-05 08:10:07.599 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873013760 Grupo 1 Checking for update
2017-09-05 08:10:07.599 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873013760 Grupo 1 Performing update
2017-09-05 08:10:07.600 VeeCeleb[8575:144729] |LOTRenderGroup 106102873015424 UserIcon contornos Checking for update
2017-09-05 08:10:07.600 VeeCeleb[8575:144729] |LOTRenderGroup 106102873015424 UserIcon contornos Performing update
2017-09-05 08:10:07.600 VeeCeleb[8575:144729] -------------------- ------------------------------- --------------------
2017-09-05 08:10:07.600 VeeCeleb[8575:144729] -------------------- ------------------------------- --------------------
2017-09-05 08:10:07.600 VeeCeleb[8575:144729] -------------------- Composition Displaying Frame 0 --------------------
2017-09-05 08:10:07.601 VeeCeleb[8575:144729] View <LOTCompositionContainer: 0x60800012d700> Displaying Frame 0
2017-09-05 08:10:07.601 VeeCeleb[8575:144729] View <LOTLayerContainer: 0x608000106ae0> Displaying Frame 0
2017-09-05 08:10:07.601 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959552 Trazo 1 Checking for update
2017-09-05 08:10:07.645 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959552 Trazo 1 Performing update
2017-09-05 08:10:07.645 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872646272 Trazado 1 Checking for update
2017-09-05 08:10:07.646 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872646272 Trazado 1 Performing update
2017-09-05 08:10:07.646 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873015296 Grupo 2 Checking for update
2017-09-05 08:10:07.646 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873015296 Grupo 2 Performing update
2017-09-05 08:10:07.646 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959440 Trazo 1 Checking for update
2017-09-05 08:10:07.647 VeeCeleb[8575:144729] |    LOTStrokeRenderer 106102872959440 Trazo 1 Performing update
2017-09-05 08:10:07.647 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872644432 Trazado 1 Checking for update
2017-09-05 08:10:07.647 VeeCeleb[8575:144729] |    LOTPathAnimator 106102872644432 Trazado 1 Performing update
2017-09-05 08:10:07.647 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873013760 Grupo 1 Checking for update
2017-09-05 08:10:07.647 VeeCeleb[8575:144729] |  LOTRenderGroup 106102873013760 Grupo 1 Performing update
2017-09-05 08:10:07.648 VeeCeleb[8575:144729] |LOTRenderGroup 106102873015424 UserIcon contornos Checking for update
2017-09-05 08:10:07.648 VeeCeleb[8575:144729] |LOTRenderGroup 106102873015424 UserIcon contornos Performing update
2017-09-05 08:10:07.648 VeeCeleb[8575:144729] -------------------- ------------------------------- --------------------
this is the debug logs for the second view animation, first view animation is running well, if I started the app with the second view directly it runs well,

**Comment by ramymabrouk** [comment] 2017-09-05 07:13
well, this was very fast :), i have removed the second view animation initialization from viewDidLoad method to viewDidAppear method, and now everything working fine, but i am not sure this is best solution

**Comment by buba447** [comment] 2017-09-05 18:02
Im sorry, your code only references one animation view? Could you please provide the code for both animation views I can help you debug!

**Comment by ramymabrouk** [comment] 2017-09-06 05:05
please find attached the sample project, to make it work just comment the viewDidLoad method in LoginController.swift and uncomment the viewDidAppear method
[lottietest.zip](https://github.com/airbnb/lottie-ios/files/1279841/lottietest.zip)

**Comment by buba447** [comment] 2017-09-07 18:49
Ahh I see what happening. Its not because you of the intialization of the view, but because you are calling `play` in view did load. A general rule of thumb is that you do not want to call animation code of any kind from `viewDidLoad`.
It works in the first on because its the root of the nav stack. But the second one, view did load is called before the LoginViewController has been presented, which calls play on the LotAnimationView. Then the view controller is added to the navstack and apples transition animation is played which lasts about .3 seconds and wipes out the LOT animation. You can leave the initialization code in `viewDidLoad` but I would move the play call into `viewDidAppear`.
Closing the issue as its not a bug.

**Closed by buba447** 2017-09-07 18:49 UTC
