### ISSUE TITLE
How to get UIImage from Lottie

### ISSUE THREAD

**Issue by AltmanMMMMM** [airbnb/lottie-ios#978] opened 2019-07-10 06:30 UTC
I want to get an UIImage from Lottie after setProgress, how can I do?

## Check these before submitting:
- [] This issue isn't related to another open issue

## This issue is a:
- [] Feature Request

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 
- [] iOS

## What Language are you in?
- [] Objective-C

**Comment by Kirow** [comment] 2019-07-12 19:12
Just use general approach:
```swift
let renderer = UIGraphicsImageRenderer(size: view.bounds.size)
let image = renderer.image { ctx in
    view.drawHierarchy(in: view.bounds, afterScreenUpdates: true)
}
```

**Comment by mofarhand** [comment] 2020-04-20 08:56
I've tried this but it doesn't work for me for some reason ...

**Comment by calda** [comment] 2022-07-13 17:10
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:10 UTC
