### ISSUE TITLE
iOS 13 render issue

### ISSUE THREAD

**Issue by balutaeugen** [airbnb/lottie-ios#1023] opened 2019-09-10 08:52 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behavior 

The animation should play just fine just like on iOS 12.4.1

## Actual Behavior

The animation is not present at all on iOS 13.1 beta 2

## Animation JSON

{"v":"5.5.2","fr":60,"ip":0,"op":91,"w":424,"h":940,"nm":"switch off","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":4,"nm":"switch off","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":-90,"ix":10},"p":{"a":0,"k":[212,627,0],"ix":2},"a":{"a":0,"k":[0,0,0],"ix":1},"s":{"a":0,"k":[292,285,100],"ix":6}},"ao":0,"shapes":[{"ind":0,"ty":"sh","ix":1,"ks":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0.001,"s":[{"i":[[-2.282,0.009],[0,-25.567],[2.202,0.289],[0,25.567]],"o":[[2.21,0],[0,25.567],[-2.316,-0.024],[0,-25.567]],"v":[[157.94,-46.281],[159.953,1.904],[157.94,46.305],[155.927,1.913]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":14.014,"s":[{"i":[[-30.12,0],[0,-26.669],[30.12,0],[0,26.669]],"o":[[30.12,0],[0,26.669],[-30.12,0],[0,-26.669]],"v":[[-25.942,-48.288],[28.596,0],[-25.942,48.288],[-80.479,0]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":24.001,"s":[{"i":[[-25.827,0],[0,-28.546],[25.827,0],[0,28.546]],"o":[[25.827,0],[0,28.546],[-25.827,0],[0,-28.546]],"v":[[-31.149,-51.804],[15.616,-0.116],[-31.149,51.571],[-77.914,-0.116]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":34.001,"s":[{"i":[[-29.116,0],[0,-26.275],[29.116,0],[0,26.275]],"o":[[29.116,0],[0,26.275],[-29.116,0],[0,-26.275]],"v":[[-26.377,-47.417],[26.343,0.158],[-26.377,47.732],[-79.097,0.158]],"c":true}]},{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":44.001,"s":[{"i":[[-26.397,0],[0,-27.689],[26.397,0],[0,27.689]],"o":[[26.397,0],[0,27.689],[-26.397,0],[0,-27.689]],"v":[[-26.711,-50.105],[21.084,0.03],[-26.711,50.165],[-74.506,0.03]],"c":true}]},{"t":74.0007591247559,"s":[{"i":[[-26.155,0],[0,-27.031],[26.155,0],[0,27.031]],"o":[[26.155,0],[0,27.031],[-26.155,0],[0,-27.031]],"v":[[-27.311,-49.12],[20.047,-0.175],[-27.311,48.769],[-74.67,-0.175]],"c":true}]}],"ix":2},"nm":"Path 2","mn":"ADBE Vector Shape - Group","hd":false},{"ty":"gs","o":{"a":0,"k":100,"ix":9},"w":{"a":1,"k":[{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":-2.001,"s":[44]},{"i":{"x":[0.833],"y":[0.833]},"o":{"x":[0.167],"y":[0.167]},"t":0.001,"s":[44]},{"t":20.0202913069319,"s":[44]}],"ix":10},"g":{"p":3,"k":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0.001,"s":[0,0.122,0.847,0.545,0.5,0.198,0.875,0.712,1,0.275,0.902,0.878]},{"t":20.0202913069319,"s":[0,0.392,0.098,0.655,0.5,0.696,0.249,0.551,1,1,0.4,0.447]}],"ix":8}},"s":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0.001,"s":[123,0],"to":[-31,0],"ti":[31,0]},{"t":20.0202913069319,"s":[-63,0]}],"ix":4},"e":{"a":1,"k":[{"i":{"x":0.833,"y":0.833},"o":{"x":0.167,"y":0.167},"t":0.001,"s":[195,0],"to":[-24.167,0],"ti":[24.167,0]},{"t":20.0202913069319,"s":[50,0]}],"ix":5},"t":1,"lc":2,"lj":2,"bm":0,"nm":"Gradient Stroke 1","mn":"ADBE Vector Graphic - G-Stroke","hd":false}],"ip":0,"op":138.138138138138,"st":-68.0480680680681,"bm":0}],"markers":[]}

**Comment by martinpristas** [comment] 2019-09-22 12:24
Same issue for me, but I've tried use main DispatchAsync 

```
DispatchQueue.main.async { [unowned self] in
// play animation
}
```

**Comment by yakushevichsv** [comment] 2019-10-23 07:30
@balutaeugen: beta, is usually not a stable version. There might be some issues.
Could you please check the issue on released iOS 13 version? 
If it's not reproduced pls close the issue: )

**Comment by calda** [comment] 2022-07-13 17:05
Closing since iOS 13.1 beta 2 is not a production iOS release and this issue may be somewhat outdated. Feel free to reopen if you're still experiencing this issue.

**Closed by calda** 2022-07-13 17:05 UTC
