### ISSUE TITLE
AnimationView with url not working properly when using cache

### ISSUE THREAD

**Issue by oslTrifork** [airbnb/lottie-ios#1539] opened 2022-03-31 10:18 UTC
Hi

We stumbled upon this issue yesterday. When you call the given initializer, there are two behaviors: 
1. Loading the animation from an URL, the scope ends and the lottieView is assigned, Animation.loadedFrom(...) fulfills, the closure is called and self.lottieView can be accessed and self.lottieView.play() works.
2. Fetching the animation from the cache, the closure is called and self.lottieView is not accessible yet, because self.lottieView hasn't been assigned yet, thus calling .play() won't work.

The code in question
```swift
  public convenience init(
    url: URL,
    imageProvider: AnimationImageProvider? = nil,
    closure: @escaping AnimationView.DownloadClosure,
    animationCache: AnimationCacheProvider? = LRUAnimationCache.sharedCache)
  {

    if let animationCache = animationCache, let animation = animationCache.animation(forKey: url.absoluteString) {
      self.init(animation: animation, imageProvider: imageProvider)
      closure(nil)
    } else {

      self.init(animation: nil, imageProvider: imageProvider)

      Animation.loadedFrom(url: url, closure: { animation in
        if let animation = animation {
          self.animation = animation
          closure(nil)
        } else {
          closure(LottieDownloadError.downloadFailed)
        }
      }, animationCache: animationCache)
    }
  }
```

There are several ways to fix it, I have come up with these: 
1. Not API breaking: Put the closure in a DispatchQueue with a small delay, although this should be considered a hack.
2. Not API breaking: Move the closure outside the initializer, make the DispatchQueue hack for backward compatibility sake but deprecate the method and encourage setting the closure afterwards.
3. API breaking: Move the closure outside the initializer, so it can be set afterwards and enforce this behavior by removing the old initializer.

Although it should be said that both 2 and 3 could be made even cleaner by encapsulating the closure in a new specific AnimationView class.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.3.0

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Steps to reproduce: 
1. Run the test project
2. tap the button
3. Close the view
4. tap the button

## Expected Behavior 
Animation plays successfully on every run

## Actual Behavior
Animation does not play because the view variable hasn't been assigned yet in the scope of the closure.

## Code Example
[TestLottie.zip](https://github.com/airbnb/lottie-ios/files/8388004/TestLottie.zip)
```swift
class ViewController: UIViewController {

    private var lottieView: AnimationView?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    deinit {
        print("deinit.ViewController")
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        lottieView = AnimationView(url: URL(string: "https://assets8.lottiefiles.com/packages/lf20_otzj2s5v.json")!, closure: { [weak self] _ in
            
            assert(self?.lottieView != nil)
            self?.lottieView?.play()
        })
        
        guard let lottieView = lottieView else {
            return
        }
        
        view.addSubview(lottieView)
        lottieView.frame = CGRect(x: 0, y: 0, width: 100, height: 100)
    }
}
```

**Comment by calda** [comment] 2022-07-13 17:24
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:24 UTC
