### ISSUE TITLE
Wrong Gradients & Bad Performance when showing them

### ISSUE THREAD

**Issue by Rapsssito** [airbnb/lottie-ios#1060] opened 2019-10-19 09:43 UTC
I am experiencing 1 FPS on UI when more than one animation with gradients is being reproduced on iOS. After some profiling, turns out that **`CGContextDrawLinearGradient`** is taking more than 90% of CPU time. Is there a missing swift optimization?
Furthermore, it looks like some gradients are not shown completely. I have attached a JSON that shows both errors.

## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 
- [x] iOS

## What Language are you in?
- [x] Swift

## Expected Behavior 
![hexgood](https://user-images.githubusercontent.com/44206249/67143541-c5c62e00-f26c-11e9-9db8-333f40e8685d.PNG)

## Actual Behavior
![hexbad](https://user-images.githubusercontent.com/44206249/67143543-c8288800-f26c-11e9-81d0-cfb6af597c1f.PNG)
_Note the white corner on the bottom left._

## Animation JSON
[Animation JSON](https://github.com/airbnb/lottie-ios/files/3746457/menuSecondaryButton.zip)

This might be related to this issue: https://github.com/airbnb/lottie-ios/issues/895

**Comment by buba447** [comment] 2019-11-20 17:10
You are experiencing two issues here.

1. The gradient is correctly displaying, its the **shape** that the gradient is filling that is incorrect. How is this shape being created? Is it a polygon with rounded corners or a shape layer?
2. The gradient performance is slow, drawing gradients is expensive, but 1fps makes me think something else is wrong. Mind sharing the after effects file so I can debug when I have time?

**Comment by Rapsssito** [comment] 2019-11-21 23:16
I think the issue is **indeed related to the gradient generation**. I have attached my AE file. It has three compositions, all look the same except for the gradient colors, but **only the composition _"comp 2"_ shows this issue**.
[menuMainButton.zip](https://github.com/airbnb/lottie-ios/files/3877181/menuMainButton.zip)

**Comment by buba447** [comment] 2019-11-22 02:22
I will look at this over the weekend!

**Comment by Rapsssito** [comment] 2019-11-22 10:03
Thank you! If you need anything from my end, tell me.

**Comment by buba447** [comment] 2019-11-25 01:59
@Rapsssito You were correct! There is a bug with gradient rendering. Looking for a fix. Will update with PR.

**Comment by Rapsssito** [comment] 2019-11-25 07:06
Thank you!

**Comment by buba447** [comment] 2019-11-25 17:02
I found the issue with your animation! After a lot of debugging I discovered that the gradient had *two colors* at the same position in after effects. If you open the gradient editor you and drag the start color you will see that there are actually two colors on top of each other:
<img width="611" alt="Screen Shot 2019-11-25 at 10 55 12 AM" src="https://user-images.githubusercontent.com/1163980/69560973-3e0dc680-0f72-11ea-8918-ca8fa8d37224.png">

Core Graphics apparently bugs out if two colors occupy the same location. I could add a check to remove the erroneous color, but that check would eat up performance. (It would require a nest for loop on locations with O(N2) complexity)

Removing one of them fixes the clipping gradient issue.
As far as performance goes, gradients are expensive to render. I might try refactoring the gradient renderer to use `CAGradientLayer` but Im not positive if that will increase performance or not.

**Comment by Rapsssito** [comment] 2019-11-25 17:36
After all, the issue was on my side. I apologize if this silly mistake took you a long time.

We definitely don't want `O(N2)` complexity with Swift... However, how is that Java outperforms Swift by that far? I can run six animations like that on solid 60 FPS on Android, but just one on 1 FPS on iOS.

**Comment by buba447** [comment] 2019-11-25 17:40
Yeah the performance for this simple animation is especially bad! Far slower than it should be. Ill dig in and see what can be done.

**Comment by telecast** [comment] 2019-12-09 07:32
@buba447 Any news on the issue? :)

**Comment by rolandleth** [comment] 2020-03-04 08:20
We're having issues with this one as well, but we checked and we don't have overlapping locations. For now we had to downgrade to `2.5.3`, any chance this will improve in a future release?

**Comment by dreampiggy** [comment] 2020-03-09 13:02
Seems the core case is the draw with Gradient. Version 2.x seems fast on this.

Any update about it ? Or can we use `CAGradientLayer` instead of draw gradient using CG code ? Or even more radical, use low-level Metal or GL code instead ?

Currently I've test the same image, with Lottie-iOS and [Samsung's rlottie implementation](https://github.com/Samsung/rlottie) on iPhone XR, the rlottie beat all the cases on animation performance.

**Comment by MobileMon** [comment] 2020-09-02 13:16
I think the issue is happening on devices WITHOUT metal

**Comment by calda** [comment] 2022-07-06 21:51
I believe the issues with gradient rendering are fixed in 3.4.0 (for both the new and old rendering engine)

**Closed by calda** 2022-07-06 21:51 UTC
Labels: bug
