### ISSUE TITLE
Bizarre / hilarious problem with files sent via Skype!  (No, really.)

### ISSUE THREAD

**Issue by smhk** [airbnb/lottie-ios#498] opened 2017-11-22 15:38 UTC
My team stumbled on to a weird one - wasted hours!

1. Mr Designer is using a current OS Mac.  Have Mr. Designer make a test.json Lottie file

2. Mr Designer sends it to Ms Programmer on skype - just drop it in the skype chat in the normal way

3. Ms Programmer is also using a current OS Mac. Both have Skype up to date.

3. Ms Programmer puts it in the iOS project - **it will not work!** Doesn't play at all.

If you put test.json on say google.drive, or, an ordinary FTP site, it works normally.

I can only guess it is due to a **line endings** issue?

I tried to massage the file and find the specific problem, but failed.

This is 100% reproducible, and yah I'm sober (fairly)

Happy Thanksgiving

**Comment by buba447** [comment] 2017-11-22 17:49
That is very strange!!
As far as I know, the JSON that comes out of body movin is not pretty print. So there are no line endings. Sounds like a problem with skype though! I would be curious to see the working JSON and then the broken skype JSON just to do a diff on the two.

**Comment by smhk** [comment] 2017-12-13 11:14
Sorry for the delay @buba447 ,

here is one of the files which does not work, bust.json

Note that I had to zip it to put it on here, so, unfortunately when you open it on your Mac who knows what that will do

Again, it is 101% reproducible, just

1 send a lottie.json file on skype
2 drop it in to Xcode
3 Run - you'll see the problem !

it almost has to be a line-ending issue (note that lottie creates "only one long line", so in other words a file-ending issue)

[bust.json.zip](https://github.com/airbnb/lottie-ios/files/1555262/bust.json.zip)

**Comment by smhk** [comment] 2018-01-09 15:23
howdy @buba447 - happy new year - did you get the example I clicked over?

this is a real, actual problem - every single team I work with has observed it!  (obviously it's easy to fix - you just .. don't use Skype to send files around - but it's fascinating!)  I have to believe it is indeed a "file ending" or "line ending" issue.

**Comment by buba447** [comment] 2018-01-09 18:45
That is strange! It must be some sort of file ending issue. Under the hood Lottie just uses the Foundation JSON deserialization, nothing too fancy. I wonder if the issue exists for other json files. Have you tried reaching out to Skype to let them know they are messing up JSON? Hahah so strange.

**Comment by smhk** [comment] 2018-01-09 19:25
Dude, it's your app but is it a good idea to close the issue?

Ya often have to massage files before you pass them off to JSON or the like..........

For example: the solution to the problem is likely as simple as either of:

- just add a new line on the end at all times
- just swap all "linefeeds" for "newlines" (or one of those damned combinations!!)

I'd say, it's very likely not so much that skype are messing up files; you know how there are annoyingly many different varieties (out of text editors and so on) of text file format; for example, when we make kode that opens up .obj, .fbx and similar text files (so as to build out 3D mesh), it's a commonplace that you have to massage the "damned line endings on the text file" - you know?

(Certainly, it's the case that "all test files should be perfect" - but they're usually not right, heh!)

Again, of course it's all you - but just a thought, the solution is probably trivial .. cheers!  Happy new year

**Comment by buba447** [comment] 2018-01-09 20:25
Hey sorry!  I actually tried opening the JSON file you sent me and it worked fine 🤷‍♂️ 
I didnt really see any path forward. Lottie is built off of the Foundation frameworks deserialization, so it should be expected that whatever JSON can be serialized by Foundation will work with Lottie. Ive not run into any issues with messaged JSON files, but Im not a skype user so I cant speak for that service in particular.  If the issue is particular to Lottie JSON and Lottie itself id love to get more info and find a way to fix it. 
It seems like you have a lot of experience with this new line issue? If you have a fix Id be happy to merge a pull request! 

Ill reopen the issue until we find a satisfying solution. Cheers!

**Comment by smhk** [comment] 2018-01-09 20:27
FWIW I will definitely try to spend some more time on it when I get a chance!  V. best, Fattie

**Comment by buba447** [comment] 2019-03-17 17:02
Lottie has been completely rewritten in Swift as of 3.0 (https://github.com/airbnb/lottie-ios/pull/777)

I am closing all issues prior to this release to reduce the noise. If you continue to run into this issues or any issue with Lottie 3.0 please open a **new ticket**

For continued support of Lottie Objective-c please point to this branch: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC

**Closed by buba447** 2019-03-17 17:02 UTC
