### ISSUE TITLE
Set imageProvider on AnimationView doesn't change providing images

### ISSUE THREAD

**Issue by nicolascabaret-tagheuer** [airbnb/lottie-ios#925] opened 2019-05-29 13:14 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0.4

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Actual Behavior

I made a simple testApp to display an `AnimationView`. When touch up a button, I configured a selector to set the `imageProvider` with a new one. The associated images are not loaded and the animation still running with old images.

I also tested to set `imageProvider` immediately on `viewDidLoad` and the behavior is the same.

After investigation, it seems `AnimationView.animationLayer?.imageProvider` and `AnimationView.animationLayer?.imageProvider` references remain different.

## Code Example

```
import UIKit
import Lottie

class ViewController: UIViewController {

    @IBOutlet weak var lottieView: AnimationView! {
        didSet {
            lottieView.loopMode = .loop
            lottieView.play()
        }
    }

    @IBAction func changeImages(_ sender: UIButton) {
        print(lottieView.imageProvider)
        lottieView.imageProvider = BundleImageProvider(bundle: Bundle.main, searchPath: "ssd")
        print(lottieView.imageProvider)
    }

    @IBAction func setBlue(_ sender: Any) {
        let colorProvider = ColorValueProvider(Color(r: 0, g: 0, b: 1, a: 1))
        lottieView.setValueProvider(colorProvider, keypath: AnimationKeypath(keypath: "**.Fill 1.Color"))
        lottieView.setValueProvider(colorProvider, keypath: AnimationKeypath(keypath: "**.Stroke 1.Color"))
    }

    @IBAction func setRed(_ sender: Any) {
        let colorProvider = ColorValueProvider(Color(r: 1, g: 0, b: 0, a: 1))
        lottieView.setValueProvider(colorProvider, keypath: AnimationKeypath(keypath: "**.Fill 1.Color"))
        lottieView.setValueProvider(colorProvider, keypath: AnimationKeypath(keypath: "**.Stroke 1.Color"))
    }
}
```

## Animation JSON
[clock.json.zip](https://github.com/airbnb/lottie-ios/files/3232599/clock.json.zip)

**Comment by buba447** [comment] 2019-05-29 17:09
If you pause the animation, then set the image provider, then play the animation, what happens?

**Comment by nicolascabaret-tagheuer** [comment] 2019-06-03 06:31
Thanks for your help! By pausing the animation, then set the image provider, then play animation, everything works. Is it the expected behavior ?
What about set the provider before any start or pause ?

**Comment by buba447** [comment] 2019-06-03 12:45
You can set the provider before playing as well. Basically theres a bug that prevents setting the provider *while* an animation is playing.

Im going to leave this issue open and ad the bug to my list.

**Comment by jeffepic** [comment] 2020-09-30 00:33
From what I can tell the issue is that the layerImageProvider is not set in AnimationView imageProvider didSet. That is why it only works by setting the image provider in the initializer.
Should be this:
public var imageProvider: AnimationImageProvider {
    didSet {
      animationLayer?.layerImageProvider.imageProvider = imageProvider
      reloadImages()
    }
  }

**Comment by KakaoTocs** [comment] 2022-01-27 06:02
(The two "ImageProviders" refer to "FilepathImageProvider" and "BundleImageProvider".)

The "reloadImages()" method calls the "imageForAset(asset) -> CGimage?" method of "ImageProvider".

Both "ImageProviders" are returned if there is "ImageAset" at the top of the "imageForAset" method logic.

"ImageAsset" is created and utilized through the "AnimationView" constructor.

That is, even if a new "ImageProvider" object is assigned to the "imageProvider" attribute of the "AnimationView" object once created, it cannot be used due to the initially created "ImageAset".

![image](https://user-images.githubusercontent.com/22838614/151299095-2f9d7a84-aff1-4d2e-8396-0fbaae1f734a.png)

**Comment by calda** [comment] 2022-07-13 17:21
I believe this bug is fixed now

**Closed by calda** 2022-07-13 17:21 UTC

**Comment by Shiva891** [comment] 2022-09-20 17:11
Anyway to update two or Three Images at a Time ?
