### ISSUE TITLE
AVSynchronizedLayer Issue

### ISSUE THREAD

**Issue by amrittrivedir** [airbnb/lottie-ios#84] opened 2017-02-13 10:42 UTC
It is not working with AVSynchronizedLayer. I am adding LOTAnimationView layer to AVSynchronizedLayer and setting begin time to CACurrentMediaTime(). But nothing happens. If I will add LOTAnimationView layer to any other CALayer then it works fine. Any suggestions for that?

**Comment by buba447** [comment] 2017-02-13 17:52
Duplicate of https://github.com/airbnb/lottie-ios/issues/30

We haven't supported AV layer yet. Will look into it

**Closed by buba447** 2017-02-13 17:52 UTC

**Comment by amrittrivedir** [comment] 2017-02-16 09:28
I am able to do it in AVSynchronizedLayer by only using _animationContainer layer. But now I can't export with same timing with avvideocomposition animation tool. I have to use repeat mode to see animation in calayers of avvideocompostion animation tool. Without repeat it's not working. And using repeat animation sometimes playing and sometimes it's not even starting.
