### ISSUE TITLE
replace value in json lottie 

### ISSUE THREAD

**Issue by s-mostafa-d** [airbnb/lottie-ios#1406] opened 2021-10-21 19:03 UTC
Hi, I am trying to change the color values ​​with the API, that is, with a color picker, the color values ​​of the file can be changed. Thank you very much for any help. These are the codes I found for this, but it did not work.

      import LottieWebParser from 'lottie-web-parser';
import animationData from './data.js';

let colorInfo = LottieWebParser.parseColors(animationData);
LottieWebParser.replaceColor([255, 0, 0, 1], colorInfo[0].path, animationData);

**Comment by calda** [comment] 2022-07-13 17:31
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:31 UTC
