### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by M0TRIX** [airbnb/lottie-ios#1823] opened 2022-11-29 16:50 UTC
assgining the Animation.named("splash-animation") causes error.

shots are attached.

![1111](https://user-images.githubusercontent.com/38591860/204592759-0b9d7d17-80f0-4473-aada-d397065644bc.png)

even using LottieAnimation.named("splash-animation") causes the same error

**Comment by calda** [comment] 2022-11-29 17:19
Are you using storyboards or xibs? If so this is a duplicate of https://github.com/airbnb/lottie-ios/issues/1771. 

If you aren't using storyboards or xibs, feel free to re-open this issue and provide more information. A sample project would be very helpful.

**Closed by calda** 2022-11-29 17:19 UTC
