### ISSUE TITLE
How to open a new view after animation finish - SwiftUI

### ISSUE THREAD

**Issue by Albuxy** [airbnb/lottie-ios#1375] opened 2021-07-06 11:26 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?
Lottie 3.0

## What Platform are you on? 

- [x] MacOS
- [] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Expected Behaviour 

After Splash Animation in Launch Screen, when finished the animation, new View opens.

## Actual Behavior

After Splash Animation in Launch Screen, when finished the animation, no view opens.

**Comment by calda** [comment] 2022-07-13 17:50
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:50 UTC
