### ISSUE TITLE
Support Even-Odd Fill Rule

### ISSUE THREAD

**Issue by rkim-homma** [airbnb/lottie-ios#43] opened 2017-02-07 02:44 UTC
[Archive.zip](https://github.com/airbnb/lottie-ios/files/756480/Archive.zip)

**Comment by rkim-homma** [comment] 2017-02-07 02:45
Bodymovin's player animates properly, but Lottie SDK does not.

**Comment by therealsalih** [comment] 2017-02-07 04:48
Hi Rkim! Just checked out your Ae file. Animation fill works properly but what Lottie doesnt support yet is multiple paths in the same group that subtract each other. nor do we support merge paths. (Squall does right now)

<img width="962" alt="screen shot 2017-02-06 at 8 42 26 pm" src="https://cloud.githubusercontent.com/assets/5893643/22678156/d92ff23c-ecac-11e6-92a6-8ae1f5a5b20d.png">

Thats why instead of seeing this

<img width="947" alt="screen shot 2017-02-06 at 8 42 30 pm" src="https://cloud.githubusercontent.com/assets/5893643/22678157/dd07894c-ecac-11e6-8cd6-35e91dce7439.png">

You're going to see this:

<img width="946" alt="screen shot 2017-02-06 at 8 42 42 pm" src="https://cloud.githubusercontent.com/assets/5893643/22678160/e14e6b2e-ecac-11e6-8af7-370b36ee0b68.png">

We're still working on that feature!

One temporary workaround is if you know your BG color to separate each of the cutouts into its own shape in its own group like this

<img width="1332" alt="screen shot 2017-02-06 at 8 47 50 pm" src="https://cloud.githubusercontent.com/assets/5893643/22678253/99fc9948-ecad-11e6-9fa8-6ec5b5f7dd37.png">

**Comment by rkim-homma** [comment] 2017-02-07 19:14
@therealsalih, thanks for the feedback.  Useful tip to know.  My belief this may be a side effect of AE's "Create shapes from Vector layers".  My workflow is a bit complex and I'm curious what sort of work flow you folks use.  DO you create the raw paths and vectors directly in AE?

My designer started from Sketch and the experimental workflow currently looks like this.
Sketch > export SVG
AI > import SVG > Release to Layers (Sequence) > rearrange layers > save
AE > import saved AI > on each AI layer Create Shapes from Vector Layer.

If I skip "Create Shapes from Vector Layer", bodymovin will export JSON + PNG images which I want to avoid.  Any ideas?

**Comment by Audiobrad** [comment] 2017-02-07 21:40
@rkim-homma I am using the same workflow. I find from time to time that sketch makes the vector files a lot more complex than they need to be and sometimes break in AE. 

I will often spend some extra time in AI going though the layers and doing as much cleanup as possible. This typically entails getting rid of all of the container boxes and excess junk brought over from sketch so only the clean assets remain. I will also combine as many related shapes with the pathfinder tool.  

If necessary, after converting the AI layers to shapes I'll use the Explode Shape Layers script from AE scripts to break up the layer and give me more control.

**Comment by therealsalih** [comment] 2017-02-08 00:21
My workflow is similar. 
Sometimes I go Sketch > PDF > AE (Create shapes from Vector Layer)
Yes there is extra container boxes and junk and sometimes depending on the complexity of the asset its easier to through deleting junk directly in AE. 

Sometimes I do Sketch > PDF > AI (deleting junk in illustrator) > AE (Create shapes from Vector Layer)

Hopefully one day we can all have a better Sketch > AE workflow

**Comment by Audiobrad** [comment] 2017-02-08 01:20
Interesting. I'll have to give the PDF route a shot. I agree. Looking forward to a better Sketch > AE workflow

**Comment by rkim-homma** [comment] 2017-02-08 23:25
@Audiobrad @therealsalih 
Glad to hear my workflow wasn't too far off.  I ended up re-drawing all of the vector paths in AI and imported them into AE without any use of odd-even fills.  Works like a charm in the Lottie sample app.

Thanks!

**Comment by therealsalih** [comment] 2017-02-09 00:28
Maybe Lottie will spur some genius sketch plugin writers to write a sketch > AE plugin... 🙏

**Comment by johnkeese** [comment] 2017-02-09 14:19
The following process, while tedious, worked for me.

1. Start with text in Illustrator (you might be able to pull in stuff from Sketch as well?)
2. Outline the text
3. For each character that requires "Merged paths" when outlining in After Effects place a hidden cut. This is easiest using the knife tool.
4. Import AI file into After Effects and "Create Shapes from Vector Layer"

![screen shot 2017-02-09 at 8 11 20 am](https://cloud.githubusercontent.com/assets/3217063/22786757/77d74aae-ee9f-11e6-99f4-b58224df65e2.png)

I've also run into issues using Pre-Comps. Seemed to work best when everything what in the root comp.

**Comment by wiille** [comment] 2017-02-18 19:02
I drew my element from scratch in Illustrator and it did not work either, I dont think it is a sketch problem.

Thank you @johnkeese for your solution until the problem is solved. It works!

**Comment by buba447** [comment] 2017-08-02 22:28
Should be fixed in Lottie 2.0! If you still have a problem please create a new issue!

**Closed by buba447** 2017-08-02 22:28 UTC
Labels: enhancement
