### ISSUE TITLE
Rendering artefacts when animation property is changed while AnimationView is offscreen.

### ISSUE THREAD

**Issue by o-huralnyk** [airbnb/lottie-ios#1067] opened 2019-11-01 13:01 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [x] This issue isn't related to another open issue

## This issue is a:
- [x] Non-Crashing Bug (Visual or otherwise)
- [x] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.3

## What Platform are you on? 

- [x] iOS 13.1.3

## What Language are you in?
- [x] Swift

## Expected Behavior 

![expected](https://user-images.githubusercontent.com/42937938/68026315-0b94e480-fcb8-11e9-8b73-30b7ab924ee4.gif)

## Actual Behavior

![actual](https://user-images.githubusercontent.com/42937938/68026318-10f22f00-fcb8-11e9-8ad7-a4cd1d9ef8fb.gif)

## Code Example
```swift
class MyViewController : UIViewController {
    
    let lottieView = AnimationView(name: "animation")
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureLayout()
    }
    
    @objc private func onButtonTap() {
        let viewController = UIViewController()
        viewController.view.backgroundColor = .lightGray
        present(viewController, animated: true) {
            self.lottieView.animation = Animation.named("animation")
        }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            viewController.dismiss(animated: true)
        }
    }

    // setup code ...
}
```

## Animation JSON

[animation.json.zip](https://github.com/airbnb/lottie-ios/files/3797961/animation.json.zip)

**Comment by buba447** [comment] 2019-11-26 15:11
It looks like the view itself is being resized and layout is occurring with implicit animations.

I cant reproduce the issue over here. Without more context it's hard to debug.

**Comment by o-huralnyk** [comment] 2019-11-26 15:27
No layout changes happened to ViewController. Here is full playground [zip archive](https://github.com/airbnb/lottie-ios/files/3892534/Playground.zip). Note that playground depend on Lottie and in my case Lottie was installed with CocoaPods. How to use CocoaPods with playgrounds here is [little guide](https://medium.com/@ant_one/adding-cocoapods-library-to-a-playground-in-3-easy-steps-8a0f22150803). I don't know how I could possibly could provide more context.

**Comment by o-huralnyk** [comment] 2019-11-26 15:33
Xcode 11.2.1, macOS Catalina 10.15.2 Beta, lottie-ios (3.1.3). It's still here.

**Comment by Waheiba** [comment] 2019-11-26 23:36
I found an older issue that reported this, it was something about a view being resized and the animation took 0.2 -> 0.5 seconds to match the new size.
It was fixed in 3.1.2 but another PR overwrote the fix.
I’m trying to find the link to the issue, and the commit that removed the fix in my browsing history.

The issue doesn’t happen on 3.1.2 but happens on versions above it. @o-huralnyk could confirm that unless we are talking about 2 different issues :D

**Comment by Waheiba** [comment] 2019-11-27 00:07
I think those might be related.
https://github.com/airbnb/lottie-ios/issues/924
https://github.com/airbnb/lottie-ios/issues/932

**Comment by o-huralnyk** [comment] 2019-11-27 07:21
@Waheiba you're right! The issue doesn't reproduce with lottie-ios 3.1.2. It seems that mentioned issues are related, but in my setup I don't change frame of AnimationView in any way. I'm using AutoLayout to position AnimationView at the center and make it square 295x295, that's all layout code. Then I present another view controller over it with _full screen_ _modal presentation style_, and when presenting animation is completed, I change animation on AnimationView (not actually change, but set the same one). After dismissing presented view controller, there is a glitch.

**Closed** 2022-07-13 17:00 UTC
