### ISSUE TITLE
How to replace image in json file

### ISSUE THREAD

**Issue by aaron-snt** [airbnb/lottie-ios#1101] opened 2019-12-14 07:23 UTC
## Check these before submitting:
- [] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [O] This issue isn't related to another open issue

## This issue is a:
- [O] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [] MacOS
- [O] iOS

## What Language are you in?
- [O] Swift
- [] Objective-C

## Expected Behavior 

I 'd like to change specific image(image_0.png) in json file.
Could you help me?

## Code Example
    @IBOutlet weak var aniview: AnimationView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        let animation = Animation.named("data")//, subdirectory: "Animations")
        if animation == nil { print("nil")}
        //aniview.frame = CGRect(x: 0, y: 0, width: 100, height: 100)
        aniview.center = self.view.center
        //aniview.contentMode = .scaleAspectFill
        let imageProvider = BundleImageProvider(bundle : Bundle.main, searchPath:"Images/")
        aniview.imageProvider = imageProvider
        aniview.animation = animation

        view.addSubview(aniview)
        aniview.play()
        
## Animation JSON

[data.json.zip](https://github.com/airbnb/lottie-ios/files/3963566/data.json.zip)
![screen](https://user-images.githubusercontent.com/44335477/70845097-01a4fa80-1e8e-11ea-81cb-42c59443bcd3.png)

**Comment by YGEqual** [comment] 2021-07-20 15:14
how do?

**Comment by calda** [comment] 2022-07-13 16:58
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 16:58 UTC
