### ISSUE TITLE
can we achieve shadow effect ?

### ISSUE THREAD

**Issue by Mushrankhan** [airbnb/lottie-ios#261] opened 2017-06-14 10:15 UTC

**Comment by buba447** [comment] 2017-06-15 18:52
This is a duplicate of https://github.com/airbnb/lottie-ios/issues/218
We dont currently have immediate plans to add support for this. We will look into it after the next major release.

**Closed by buba447** 2017-06-15 18:52 UTC

**Comment by Mushrankhan** [comment] 2017-06-16 14:26
Ok. Thanks for immediate reply. We are waiting for this.

**Comment by hdinhof1** [comment] 2020-01-03 18:32
You can add a shadow to your view. Make sure `masksToBounds = false`

```
        layer.shadowOffset = CGSize(width: 0, height: 20)
        layer.shadowRadius = 20
        layer.shadowColor = UIColor.black.cgColor
        layer.shadowOpacity = 0.30
        layer.masksToBounds = false
```
