### ISSUE TITLE
oc cannot create a AnimationView with file path

### ISSUE THREAD

**Issue by yanganggithub** [airbnb/lottie-ios#1103] opened 2019-12-19 02:57 UTC
how to create a AnimationView with the file path???

**Comment by SandraMarcelaHerreraArriaga** [comment] 2019-12-23 21:42
Hello @yanganggithub  :)  

Try with this code, I think you need to know how to use the `Animation.filepath` initialization right?

I hope this could be helpful for you, if not write in more detail what are the problem you have and I am happy to help you :D 
```
let view = AnimationView()
let path = Bundle.main.path(forResource: "checkMark",
                                ofType: "json") ?? ""
    view.animation = Animation.filepath(path)
```

**Comment by calda** [comment] 2022-07-13 16:58
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 16:58 UTC
