### ISSUE TITLE
Rubberhose to lottie - animation works except limbs

### ISSUE THREAD

**Issue by MalcolmnDEV** [airbnb/lottie-ios#1362] opened 2021-05-31 09:16 UTC
## This issue is a:
Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?
Lottie 3.2.3

## What Platform are you on? 
- [] iOS

## What Language are you in?
- [] Swift

## Expected Behavior 
See animation play inside the iOS app with no drop in frame: https://lottiefiles.com/share/r8dgfwru

## Actual Behavior
Animation plays with limbs dropping off on a frame or two

## Code Example
`fileprivate let exampleAnimation: AnimationView = {        
let animationView = AnimationView.init(name: "animation_example")        
animationView.loopMode = .playOnce       
animationView.backgroundBehavior = .pauseAndRestore       
  return animationView    
}()`

## Animation JSON

[animation_example.json.zip](https://github.com/airbnb/lottie-ios/files/6569176/animation_example.json.zip)

**Comment by MalcolmnDEV** [comment] 2021-05-31 09:17
Following on from this issue logged on the web repo: https://github.com/airbnb/lottie-web/issues/2335

We got the animation to show the limbs from Rubberhose but we are experiencing that some of the limbs drop off in frames once or twice

**Comment by MalcolmnDEV** [comment] 2021-06-14 14:41
Any update on this ?

**Comment by calda** [comment] 2022-08-04 01:02
The new Core Animation rendering engine should fix the performance issues with this animation, but the new engine doesn't support `MatteMode.invert` yet (which this animation uses to render the character's arms). Closing as a dupe of https://github.com/airbnb/lottie-ios/issues/1655, since fixing that issue should fix this one as well.

**Closed by calda** 2022-08-04 01:02 UTC
