### ISSUE TITLE
Assign a downloaded animation file to an existing LOTAnimationView instance

### ISSUE THREAD

**Issue by YL1970** [airbnb/lottie-ios#1154] opened 2020-03-24 16:01 UTC
Hi, 
IOS
I have a view with an instance of LOTAnimationView in it.
This view needs to dynamically show different animation files that are downloaded from a server.
Essentially, the animation files are date based. These files cannot be part of the project/IPA file.
I download the file to the apps sandbox and retrieve its URL.
I can verify that the file was actually downloaded.
lotCategoryDelta is a reference to my LOTAnimationView.
I tried the following code but it did not work:

let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
let url = URL(fileURLWithPath: path).appendingPathComponent(fileName) self.lotCategoryDelta.animation = url.path
 self.lotCategoryDelta.play()

Please advise. 
Thank you.
Yigal

## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Not sure. In my pods file I have lottie listed as:
 pod 'lottie-ios'

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Code Example
let path = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0]
let url = URL(fileURLWithPath: path).appendingPathComponent(fileName) self.lotCategoryDelta.animation = url.path
 self.lotCategoryDelta.play()

**Comment by chen326207167** [comment] 2020-09-11 08:16
I have the same problem with you

**Comment by EdwinXiang** [comment] 2021-03-29 06:37
I have the same problem with you ? do you have resloved?

**Comment by calda** [comment] 2022-07-13 16:50
Closing since this sounds like an iOS SDK issue and not a bug with the Lottie framework. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd like advice on an issue like this :)

**Closed by calda** 2022-07-13 16:50 UTC
