### ISSUE TITLE
Animation in TableViewCell still playing after cell has been removed

### ISSUE THREAD

**Issue by s6joui** [airbnb/lottie-ios#1177] opened 2020-04-14 10:43 UTC
## Check these before submitting:
- [X] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)

## Which Version of Lottie are you using?

Lottie 3.0

## What Platform are you on? 

- [X] iOS

## What Language are you in?
- [X] Swift

## Expected Behavior 

I would expect that the animations would stop after a cell is no longer in a TableView.

## Actual Behavior

Checking with Time Profiler I can see that lottie is being called all the time even though the cell is no longer displayed.

My current temporary solution is to override `didEndDisplaying cell` and call `animationView.stop()` from there. Is this how we are expected to deal with this or should lottie handle it?

## Code Example
```
class TestViewController: UITableViewController {
    
    var isLoading = true
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.register(LoadingCell.self, forCellReuseIdentifier: "LoadingCell")
    }
    
    override func viewDidAppear(_ animated: Bool) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 5.0) {
            self.isLoading = false
            self.tableView.reloadData()
        }
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if isLoading {
            let loadingCell = tableView.dequeueReusableCell(withIdentifier: "LoadingCell", for: indexPath)
            return loadingCell
        }
        return UITableViewCell()
    }

}

class LoadingCell: UITableViewCell {
    
    let anim = AnimationView()
    
    override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    func setup() {
        anim.translatesAutoresizingMaskIntoConstraints = false
        anim.backgroundBehavior = .pauseAndRestore
        anim.animation = Animation.named("loading-animation", bundle: Bundle.main)
        anim.loopMode = .loop
        addSubview(anim)
        anim.heightAnchor.constraint(equalToConstant: 64).isActive = true
        anim.widthAnchor.constraint(equalToConstant: 64).isActive = true
        anim.centerYAnchor.constraint(equalTo: centerYAnchor).isActive = true
        anim.centerXAnchor.constraint(equalTo: centerXAnchor).isActive = true
        anim.play()
    }

}
```

**Comment by calda** [comment] 2022-07-13 17:44
Closing since this is a question and not a bug report. Feel free to start a [discussion](https://github.com/airbnb/lottie-ios/discussions) if you'd still like support.

**Closed by calda** 2022-07-13 17:44 UTC
