### ISSUE TITLE
Lottie IOS Freezing half way through animation

### ISSUE THREAD

**Issue by robotdjman** [airbnb/lottie-ios#1190] opened 2020-05-05 05:27 UTC
## Check these before submitting:
- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [X] This issue isn't related to another open issue

## This issue is a:
- [X] Non-Crashing Bug (Visual or otherwise)
- [] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.8 

## What Platform are you on? 

- [] MacOS
- [X] iOS

## What Language are you in?
- [X] Swift
- [] Objective-C

## Expected Behavior 

Run animation fully once, or play the intro, then play the loop

## Actual Behavior

Freezes almost exactly halfway, where my keyframes end, and Adobe AE continues with a loopout() expression. Animation plays just fine in body motion, as well as online at lottiefiles.com

## Code Example
Neither

`        
introAnimation.play(fromFrame: 0,
                            toFrame: 119,
                            loopMode: LottieLoopMode.playOnce,
                            completion: { (finished) in
                                if finished {
                                    //self.playLoop()
                                    print("finished")
                                } else {
                                    print("Animation cancelled")
                                }
        })
`

or 

`introAnimation.play()`
completly play the animation

## Animation JSON

https://assets10.lottiefiles.com/packages/lf20_XvHY9T.json

**Comment by OscarGarPer** [comment] 2020-05-05 09:53
We are having the same issue. I can add: the same animation that now freezes played fine until some weeks ago. What we have change in these weeks: our test devices has been updated to last iOS 13 stable / public release, xcode has been updated to last stable / public release and lottie pod has been updated to 3.1.8 version. Not all animations are freezing, but the ones that do it, do always on same frame. If we put the .play in viewWillAppear and show the view a couple of times the animation play some frames on every iteration and we can see the full animation.

Our code is really simple:

`override func viewDidLoad() {
        super.viewDidLoad()
        animationView.loopMode = .playOnce
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        animationView.play()
    }`

**Comment by nathan-mohemian** [comment] 2020-05-05 13:48
One more with the exact same issue: freezes at halfway point until loop restarts.

Simple replication steps: put [this simple animation](https://assets7.lottiefiles.com/packages/lf20_BU0tkr.json) into the Example project in the lottie-ios repo and test there. I can confirm also that this animation plays correctly in the web player.

**Comment by OscarGarPer** [comment] 2020-05-05 14:28
I have checked that animationDidStop from AnimationContext is called when the animation freezes. This is a log for the same animation played a couple of times:

/* First iteration, the animation plays perfectly */
2020-05-05 13:41:37 +0000 LottieLog: animationDidStop finishedFlag: true FRAME: 0.0
2020-05-05 13:41:37 +0000 LottieLog: playFullAnimation: true FRAME: 180.0

/* Second, third and foruth iterations, the animation stops, I call to play again and then finish fine */
2020-05-05 13:41:54 +0000 LottieLog: animationDidStop FRAME: 25.645869076251984
2020-05-05 13:41:54 +0000 LottieLog: playFullAnimation: false FRAME: 25.645869076251984
2020-05-05 13:41:57 +0000 LottieLog: animationDidStop FRAME: 25.645869076251984
2020-05-05 13:41:57 +0000 LottieLog: playFullAnimation: true FRAME: 180.0

2020-05-05 13:52:29 +0000 LottieLog: animationDidStop FRAME: 26.315152645111084
2020-05-05 13:52:29 +0000 LottieLog: playFullAnimation: false FRAME: 26.315152645111084
2020-05-05 13:52:31 +0000 LottieLog: animationDidStop FRAME: 26.315152645111084
2020-05-05 13:52:31 +0000 LottieLog: playFullAnimation: true FRAME: 180.0

2020-05-05 13:52:35 +0000 LottieLog: animationDidStop FRAME: 18.96904483437538
2020-05-05 13:52:35 +0000 LottieLog: playFullAnimation: false FRAME: 18.96904483437538
2020-05-05 13:52:37 +0000 LottieLog: animationDidStop FRAME: 18.96904483437538
2020-05-05 13:52:37 +0000 LottieLog: playFullAnimation: true FRAME: 180.0

playFullAnimation is a method that I wrote:

`func playFullAnimation(completionFunc: (() -> Void)? = nil) {`
`  self.play { (finished) in`
`    if (finished) {`
`      completionFunc?()`
`    }`
`    else {`
`      self.playFullAnimation(completionFunc: completionFunc)`
`    }`
`  }`
`}`

**Comment by robotdjman** [comment] 2020-05-05 16:12
Just another update, it seems to try and play the animation all the way through but can’t. Adding a completion block to the play method runs 2 seconds after the animation freezes (which is exactly how much the animation has left after freezing).

**Comment by OscarGarPer** [comment] 2020-05-06 07:28
I have continued investigating. Before the update we were using lottie version 3.0.4. With this version all animations plays fine. With version 3.1.6 the animations freezes. I'm sure we can find the exact version that introduces the bug.

**Comment by nathan-mohemian** [comment] 2020-05-06 07:56
I just retested in both a private project and the lottie-ios/Example project and am still seeing the same bugged behavior with 3.0.4 using the test animation I posted above.

@OscarGarPer are you 100% sure 3.0.4 works for you? What version of iOS are you testing on?

**Comment by OscarGarPer** [comment] 2020-05-06 08:20
Hi,

I'm testing with xcode 11.4.1, iOS deployment target 11.0 and right now iphone 8 with iOS 13.4.1.

With version 3.0.4 all our animations play fine. With version 3.0.7 almost all animations freeze. For us reverting lottie to 3.0.4 is a temp solution.

I have tested again and I have record a video (I can't publich the video, is for internal use for now) and yes, I'm sure that for our project / animations version 3.0.4 works fine, but version 3.0.7 freezes.

**Comment by nathan-mohemian** [comment] 2020-05-06 08:29
Interesting! Thanks for investigating, I wonder what's different about my setup?

Can you try out the lottie-ios Example project and paste in [the test animation](https://assets7.lottiefiles.com/packages/lf20_BU0tkr.json) I posted earlier?

If that works that would basically rule out any project or animation differences.

**Comment by OscarGarPer** [comment] 2020-05-07 12:27
Hi,

I have tested nathan-mohemian animation on my project and record two videos. The code is exactly the same:

override func viewWillAppear(_ animated: Bool) {
        animationView.play { (finished) in
            if (finished && self.titleLabel.isHidden == true){
                self.animateTitleAndBodyText()
            }
        }
}

With lottie version 3.0.4 the animation plays fine the first time viewWillAppear is called and then the last frame is fixed (this is our desired behavior):

https://drive.google.com/open?id=1H0v1Zs3FXzejV7vbCpLEE1xSGBqtNCA6

With lottie version 3.0.7 the animation plays fine the first time in the first view controller, but the next time (on next view) it stops and when the animation finishes (and the title is shown) .play in viewWillAppear starts the animation again:

https://drive.google.com/open?id=1mhqUSU7LfRRXUOmDnHqjsUEuH_NPRQiT

If I have time I will try with a new empty project.

**Comment by nathan-mohemian** [comment] 2020-05-08 07:38
@OscarGarPer Hmm, I don't think your videos show correct behavior (though it's hard to tell). In a web player, my animation should look like this, and do a full rotation starting from the bottom point (like so):

<details>

<summary>Click to show GIF</summary>

![animation](https://user-images.githubusercontent.com/43135304/81381998-f0df7480-910d-11ea-9589-603e9de3bdc8.gif)

</details

When I test on device, I see the smaller circle freeze right at the top of the larger circle (exact halfway through the full animation). It looks like that's what's happening in your 3.0.4 video, the 3.0.7 video also seems broken, but in a slightly different way.

I should have more time to look into this today, I'll make some ready-to-test forks of the example project so it's easy for people to quickly reproduce this. We need to figure out whether this bug was introduced by an iOS update, or a lottie-ios release, or what.

**Comment by OscarGarPer** [comment] 2020-05-08 10:10
Ok. I didn't now how the animation should look like.

Now I think there are 2 problems on this thread. One is relative to the json animation, because in my project, if I play it on loop mode there are no freezes but the orange dot moves only from bottom to top. So maybe there is something in @nathan-mohemian animations that is not fully compatible with iOS library (with had similar problem with animations that worked fine on web and android, but not on iOS and we fixed them fixing the animation).

And another problem is that all animations that play fine on older versions of lottie, started failling on versions > 3.0.4

@robotdjman have you tried your animation with lottie 3.0.4? Does it fix your problem?

**Comment by nathan-mohemian** [comment] 2020-05-08 12:29
@OscarGarPer I think you're right about there being two separate issues here.

@robotdjman and I both mentioned using `loopout("cycle", 0)` to control the latter half of the animation, but I guess that falls under "expressions" in the [compatability matrix](https://github.com/airbnb/lottie/blob/master/supported-features.md). Which would explain why both of us see the same issue: animation freezing halfway through loop. If that's the case we're both seeing the same issue because we're using unsupported features. I did a bit of digging and found this old issue which seems to confirm that loopOut is an unsupported feature: https://github.com/airbnb/lottie-ios/issues/951 If this is really true then we should close this ticket and move on.

@OscarGarPer Your bug is probably something different then the one described in this issue then 🤔 I'd be happy to help reproduce your issue if you give me an animation to test, you helped me out earlier.

**Comment by robotdjman** [comment] 2020-05-08 22:42
Yeah @nathan-mohemian, removing my loopout expression seemed to solve the issue for me, I made an intro, then a different file for the loop, and switched them out once I needed to have it loop. I have downgraded to Lottie 3.0.4, but unfortunately did nothing for my issue, it seemed to be the After Effects Expression

**Comment by nathan-mohemian** [comment] 2020-05-11 11:18
Ok good to know that's the root cause. @robotdjman can you close this issue then? Looks like this one was us simply using an unsupported feature.

@OscarGarPer  I recommend you make a new issue with your specific problem so that readers don't have to detangle these two separate issues. Thanks for your help in replicating this.

**Closed** 2020-05-11 17:07 UTC
