### ISSUE TITLE
Lottie Swift with Xcode 11.2 Crashes when creating AnimationView 

### ISSUE THREAD

**Issue by gabors** [airbnb/lottie-ios#1066] opened 2019-10-31 22:19 UTC
@thedrick 

- [x] The issue doesn't involve an [Unsupported Feature](https://github.com/airbnb/lottie-ios/blob/master/README.md#supported-after-effects-features)
- [] This issue isn't related to another open issue

## This issue is a:
- [] Non-Crashing Bug (Visual or otherwise)
- [x] Crashing Bug
- [] Feature Request
- [] Regression (Something that once worked, but doesn't work anymore)

## Which Version of Lottie are you using?

Lottie 3.1.3 release, nut current master branch also crashes
Using Lottie as a SwiftPM package

## What Platform are you on? 

- [] MacOS
- [x] iOS

## What Language are you in?
- [x] Swift
- [] Objective-C

## Actual Behavior

<img width="1253" alt="Screen Shot 2019-10-31 at 16 19 04" src="https://user-images.githubusercontent.com/3587589/67990015-3882c200-fbfa-11e9-9c3f-8b6931e4fb03.png">

## Code Example

let x = AnimationView(name: "test")

## Animation JSON
Any JSON animation from your example project

**Comment by danielsaidi** [comment] 2019-11-01 07:01
I just noticed this as well.

**Comment by mborsten** [comment] 2019-11-01 08:38
I get this crash too with Xcode 11.2. It happens when setting an animation on the animation view, not when creating the animation view.

**Comment by makoni** [comment] 2019-11-01 09:21
Same for me. That happened with Xcode 11.2 beta too

**Comment by mborsten** [comment] 2019-11-01 11:27
This crash does not seem related to 13.2. It happens on simulator and devices running 13.2 and 12.4.2.

**Comment by danielsaidi** [comment] 2019-11-01 11:38
It's a compiler issue, right? I can run our prod app with the latest Lottie version when it's built with the 5.1 compiler, but not with the latest compiler.

**Comment by gabors** [comment] 2019-11-01 17:14
> It's a compiler issue, right? I can run our prod app with the latest Lottie version when it's built with the 5.1 compiler, but not with the latest compiler.

Well yeah, if you build with Xcode 11.1 or earlier you're fine. 
Issue is using Xcode 11.2 which you need if you want to debug on iOS 13.2.

**Comment by thedrick** [comment] 2019-11-01 18:45
Could someone set up a sample project or link me to an animation that is causing this crash? I can't reproduce this on my end.

**Comment by rouviere** [comment] 2019-11-01 20:23
I am having the same problem. Anything Lottie on Xcode 11.2 will not run. Here is a link to a repository: https://github.com/rouviere/lottie

**Comment by thedrick** [comment] 2019-11-01 22:10
I just verified this seems to only happen when you include Lottie through SPM. Does this also happen with CocoaPods? I tested the same code with including Lottie files manually vs. using SPM to download the package and it only crashes when using SPM

**Comment by gabors** [comment] 2019-11-01 22:18
> I just verified this seems to only happen when you include Lottie through SPM. Does this also happen with CocoaPods? I tested the same code with including Lottie files manually vs. using SPM to download the package and it only crashes when using SPM

I only tried with swift pm.

**Comment by danielsaidi** [comment] 2019-11-02 07:07
We also use SPM. I can go back to CocoaPods and see if it solves the problem.

**Comment by mborsten** [comment] 2019-11-02 09:19
I’m using SPM and it crashes. I’ve just tried this with Cocoapods and then it doesn’t crash.

**Comment by ydnar** [comment] 2019-11-02 18:31
The issue is related to stripped generic symbols from a SPM package. 

Try disabling dead code stripping on your app’s project: DEAD_CODE_STRIPPING = NO 

https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564

**Comment by makoni** [comment] 2019-11-04 08:39
Adding with Carthage also works. Lottie doesn't crash

**Comment by buba447** [comment] 2019-11-04 18:04
Hey everyone! Im looking into this issue and working to see if it can be fixed code side. For now use the solution provided by @ydnar above.

**Comment by buba447** [comment] 2019-11-04 18:07
An update, theres a swift bug filed [here](https://bugs.swift.org/browse/SR-11564) for the same issue on another repo. Please add your comments there so we can get a quick fix from apple!

**Comment by danielsaidi** [comment] 2019-11-04 18:46
I can confirm that disabling dead code stripping works. However, I don’t know if this causes any side-effects.

**Comment by abrahamNefi** [comment] 2019-11-04 23:48
i have disable dead code stripping code and still crashing in this line when try to load xib files with lottie Animated View:
let animationLayer = AnimationContainer(animation: animation, imageProvider: imageProvider, textProvider: textProvider)
and in console log: [Storyboard] Unknown class AnimationView in Interface Builder file.

**Comment by danielsaidi** [comment] 2019-11-05 11:02
If you press enter in the textfield where the storyboard refers AnimationView, does it resolve to being defined in Lottie?

**Comment by rouviere** [comment] 2019-11-05 15:11
Confirmed that yndar's solution works.

**Comment by genuinezack** [comment] 2019-11-14 17:08
Was this related to the 11.2 issue that lead to Apple pulling that version? If so, it should fixed as of 11.2.1. Can someone who was running into this issue confirm whether it's still happening in 11.2.1?

**Comment by danielsaidi** [comment] 2019-11-14 17:40
I can check it out soon 👍

**Comment by shial4** [comment] 2019-11-17 23:27
11.2.1 still encountering this crash

**Comment by asowers1** [comment] 2019-11-26 14:45
Switching from SPM back to Cocoapods worked for me.

**Comment by danielsaidi** [comment] 2019-11-27 21:50
Yes, CocoaPods doesn't have this problem. @gabors Do you think it would be good to clarify in the title that it only happens with SPM?

**Comment by gabors** [comment] 2019-11-28 03:05
> Yes, CocoaPods doesn't have this problem. @gabors Do you think it would be good to clarify in the title that it only happens with SPM?

Yes sir this issue started when I switched from using Carthage to SwiftPM

**Comment by duraz** [comment] 2019-12-01 21:34
SwiftPM for me is the issue. Using Lottie from Carthage worked. Now though the animation is not nil loaded from json, setting the animation crash the app.

**Comment by bozidarsevo** [comment] 2020-01-03 08:47
I just tried it with Xcode 11.3 and using Lottie 3.1.5 with SPM and it works ok now with DEAD_CODE_STRIPPING = YES. Also this link https://bugs.swift.org/plugins/servlet/mobile#issue/SR-11564 was mentioned above and there somebody mentioned that it is fixed.

**Comment by vladislavsosiuk** [comment] 2020-04-01 12:41
I tried to add AnimationView in xib file and I got crash.
Once I created AnimationView in code crash gone

**Comment by dvlp-jrs** [comment] 2020-04-05 04:36
I am getting the error at
let animationLayer = AnimationContainer(animation: animation, imageProvider: imageProvider, textProvider: textProvider)
[Storyboard] Unknown class _TtC4_VPN13AnimationView in Interface Builder file.
Installed using cocoapods and running on Xcode 11.4

**Comment by vladislavsosiuk** [comment] 2020-04-20 21:48
> I am getting the error at
> 
> let animationLayer = AnimationContainer(animation: animation, imageProvider: imageProvider, textProvider: textProvider)
> 
> [Storyboard] Unknown class _TtC4_VPN13AnimationView in Interface Builder file.
> 
> Installed using cocoapods and running on Xcode 11.4
> 
> 

Try to create it from code

**Comment by iamsanketray123** [comment] 2020-07-21 06:36
My app was crashing when I added a view from a XIB. It was fixed when I added it via code.

**Comment by AyushKovind2** [comment] 2020-10-18 12:02
> I just verified this seems to only happen when you include Lottie through SPM. Does this also happen with CocoaPods? I tested the same code with including Lottie files manually vs. using SPM to download the package and it only crashes when using SPM

Yes it is also happening with Cocoapods. Whenever I am using lottieanimation in my view, it crashes

**Comment by shimazu2** [comment] 2021-01-19 14:59
@iamsanketray123  @vladislavsosiuk 

Can you give more details about the crash from XIB.
I can't recreate it (Xcode 12.2 & Lottie 3.1.5).

Thanks.

**Comment by vladislavsosiuk** [comment] 2021-01-19 15:01
> @iamsanketray123 @vladislavsosiuk
> 
> Can you give more details about the crash from XIB.
> I can't recreate it (Xcode 12.2 & Lottie 3.1.5).
> 
> Thanks.

@shimazu2 simply use AnimationView in xib and app will crash in runtime while awaking xib or trying to animate it, i don't remember for sure as it was long time ago

**Comment by shimazu2** [comment] 2021-01-19 15:06
> > @iamsanketray123 @vladislavsosiuk
> > Can you give more details about the crash from XIB.
> > I can't recreate it (Xcode 12.2 & Lottie 3.1.5).
> > Thanks.
> 
> @shimazu2 simply use AnimationView in xib and app will crash in runtime while awaking xib or trying to animate it, i don't remember for sure as it was long time ago

@vladislavsosiuk Well... thats exactly what I have tried.. no crash.

**Comment by vladislavsosiuk** [comment] 2021-01-19 15:12
@shimazu2 the only thing i can to tell is that i used lottie 3.1.6

**Comment by Saurabh-vegans** [comment] 2021-04-02 11:05
> I tried to add AnimationView in xib file and I got crash.
> Once I created AnimationView in code crash gone

I'm also having the same issue then I noticed that I have to select `Lottie` in modules

**Comment by Viveco** [comment] 2022-01-26 02:22
use xib crash， need code

**Comment by calda** [comment] 2022-07-13 16:59
Closing since this seems like a potentially outdated issue. Feel free to re-open if you're still experiencing this issue.

**Closed by calda** 2022-07-13 16:59 UTC

**Comment by deremakif** [comment] 2023-05-25 11:29
I have a similar issue. I used LottieAnimationView. My app crashes on iPhone 6 with iOS 12 which is a real device.

When I try it on a simulator with the same config, iPhone 6 with iOS 12, it works as expected. My Podfile:

    pod 'lottie-ios', '~> 4.0.1', :modular_headers => true
